### PR TITLE
Disable buffering of output from applications so logging appears immediately.

### PR DESCRIPTION
**Pull request by GrahamDumpleton**
This addresses #157 and ensures that any output from a Python web application will be captured in logs immediately. Without this option, the output being logged can be buffered in process, meaning that if the application crashes, log output can be lost. The delay in logging messages even in normal case can be confusing where user is expecting to see debug messages from an application.

This change affects ``gunicorn`` and ``waitress`` WSGI servers, Django development server, and any other custom Python web application using ``app.py``. It is not relevant to ``mod_wsgi-express`` or ``uWSGI`` as they already set up capture of ``stdout`` and ``stderr`` in a way that results in messages being output immediately with no buffering.

Note that there are no specific tests as is can't easily be validated with the test infrastructure. One would need to deploy the updated standalone test application with existing S2I builder and then new version. Then hit the application with siege. With the existing S2I builder the log messages are delayed and show up in batches as flushing of buffered output occurs. With changes, the log messages appear straight away.

### CODE REVIEW

**Comment by pkubatrh** [comment]
LGTM
We should retest however as the last run seems to have failed on pulling OS images. I wonder if I can run some of the tests...

**Comment by pkubatrh** [comment]
[test]

**Comment by GrahamDumpleton** [comment]
[test]

**Comment by hhorak** [comment]
Sorry for delay, can you rebase, please?

**Comment by GrahamDumpleton** [comment]
[test]

**Comment by GrahamDumpleton** [comment]
[test]

**Comment by GrahamDumpleton** [comment]
@rhcarvalho Can you trigger test on this one as well.

**Comment by omron93** [comment]
[test]

**Comment by torsava** [comment]
Looks good to me! I'd say this is overdue for a merge.

**Pull request merged**
