### PR TITLE
fix: fail testsuite if app build fails

### PR DESCRIPTION
**Pull request by zmiklank**
This part of a code is getting hard to read :).

Could be a nice target in some refactoring. I could get to it in the future.

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
I decided to do small refactoring now.

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
[test]

**Review by frenzymadness — APPROVED** [review]
The changes here look good to me. Thank you. Feel free to merge them, if you are happy with them.

**Pull request merged**
