### PR TITLE
Fix OpenShift failures

### PR DESCRIPTION
**Pull request by phracek**
This pull request fixes OpenShift 3,4 failures.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
It looks like OpenShift 4 is down. I will reinstall it or try it later on. May be an infrastructure issue.

**Comment by frenzymadness** [comment]
The changes look good to me so far.

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
Fedora tests are failing for this reason:
```bash
Removing intermediate container 5eda1ee7bcc8
Step 7/15 : RUN INSTALL_PKGS="python3 python3-devel python3-setuptools python3-pip nss_wrapper         httpd httpd-devel atlas-devel gcc-gfortran libffi-devel         libtool-ltdl enchant redhat-rpm-config" &&     dnf -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     dnf -y clean all --enablerepo='*'
 ---> Running in 52622d818944

[91m[0mFedora 35 - x86_64                              0.0  B/s |   0  B     00:00    
[91mErrors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
[0m[91mError: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
[0mThe command '/bin/sh -c INSTALL_PKGS="python3 python3-devel python3-setuptools python3-pip nss_wrapper         httpd httpd-devel atlas-devel gcc-gfortran libffi-devel         libtool-ltdl enchant redhat-rpm-config" &&     dnf -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     dnf -y clean all --enablerepo='*'' returned a non-zero code: 1
make[1]: Leaving directory `/tmp/sclorg/s2i-python-container'
make[1]: *** [3.10] Error 1
make: *** [build-serial] Error 2
```

RHEL8 tests are failing for this reason:

```bash
    writing top-level names to /tmp/pip-pip-egg-info-1dbt1un4/psycopg2_binary.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-1dbt1un4/psycopg2_binary.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/97/00/ed4c82364741031d745867f83820d4f373aa891098a5785841850491c9ba/psycopg2-binary-2.8.5.tar.gz#sha256=ccdc6a87f32b491129ada4b87a43b1895cf2c20fdb7f98ad979647506ffc41b6 (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement psycopg2-binary==2.8.5 (from versions: 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9, 2.9.1, 2.9.2, 2.9.3)
ERROR: No matching distribution found for psycopg2-binary==2.8.5
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/opt/app-root/bin/python3.9 -m pip install --upgrade pip' command.
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": error while running runtime: exit status 1

OpenShift tests for ubi8/python-39-minimal:1 failed.
```

**Comment by phracek** [comment]
@frenzymadness The pull request is ready for review. The errors for Fedora and RHEL8 - OpenShift 4 are mentioned in the comment.

Nothing related to OpenShift tests, Python related tests.

**Comment by frenzymadness** [comment]
> Fedora tests are failing for this reason:

This should be fixed in Docker 20.10.10 released on the 26th of October last year. Could we somehow update the Docker we use on the Testing farm?

> RHEL8 tests are failing for this reason:

I see where the problem probably lies. The problem is that we are still testing the old version of django-ex in the openshift. Other tests have this: https://github.com/sclorg/s2i-python-container/blob/943aee5f3875a2726ee20d31b44d3b2a6d1cc041/3.9/test/run#L220-L224

But test-openshift does not use the condition. Will take a look at how to implement it. I'm afraid that the functions we have there do not support the "@" separator for branches yet.

**Comment by frenzymadness** [comment]
I've tried to use the beforementioned code for Openshift. Let's see what happens. [test-all]

**Comment by frenzymadness** [comment]
Error does not seem to be related to Python tests:
```
Copying blob sha256:a571a39ddc82ec794de442c889c4b16b455fb657311cc2ae6a636231894a719d
Error: Error copying image to the remote destination: Error writing blob: Error uploading layer to https://docker-registry.upshift.redhat.com/v2/rhscl-ci-testing/python-27/blobs/uploads/0a80c424-9fa0-4044-9965-1e66866083c7?_state=uqhZrOxzciQIlWRmpG7eXdOTmkaZEd-L2vAZ7523AaR7Ik5hbWUiOiJyaHNjbC1jaS10ZXN0aW5nL3B5dGhvbi0yNyIsIlVVSUQiOiIwYTgwYzQyNC05ZmEwLTQwNDQtOTk2NS0xZTY2ODY2MDgzYzciLCJPZmZzZXQiOjg1MzQ1Njc5LCJTdGFydGVkQXQiOiIyMDIyLTAxLTI0VDE3OjAzOjA4WiJ9&digest=sha256%3A15b14df1b76507f3f9ab6187539a86e6c6fe57514894775598e67c9767ca62a0: error parsing HTTP 400 response body: unexpected end of JSON input: ""

OpenShift tests for ubi8/python-27:2.7 failed.
make: *** [common/common.mk:106: test-openshift-4] Error 125
```
Let's try it once more. [test-openshift]

**Comment by phracek** [comment]
I have checked the error for `RHEL8 - OpenShift 4` and:

`oc status` shows:

```bash
oc status
In project sclorg-test-7656 on server https://api.core-serv-ocp.hosted.psi.rdu2.redhat.com:6443

svc/postgresql - 172.30.78.210:5432
  dc/postgresql deploys istag/postgresql:10
    deployment #1 deployed 9 minutes ago - 1 pod

http://python-testing-sclorg-test-7656.apps.core-serv-ocp.hosted.psi.rdu2.redhat.com (svc/python-testing)
  dc/python-testing deploys istag/python-testing:latest <-
    bc/python-testing source builds https://github.com/sclorg/django-ex.git#master on istag/python:3.9-minimal
      build #1 failed 8 minutes ago - 064993e: Mention the latest version in the main readme (Lumír 'Frenzy' Balhar <lbalhar@redhat.com>)
    deployment #1 waiting on image or update

Errors:
  * build/python-testing-1 has failed.

1 error, 1 warning identified, use 'oc status --suggest' to see details.
```

`oc status --suggest` shows:

```bash
oc status --suggest
In project sclorg-test-7656 on server https://api.core-serv-ocp.hosted.psi.rdu2.redhat.com:6443

svc/postgresql - 172.30.78.210:5432
  dc/postgresql deploys istag/postgresql:10
    deployment #1 deployed 9 minutes ago - 1 pod

http://python-testing-sclorg-test-7656.apps.core-serv-ocp.hosted.psi.rdu2.redhat.com (svc/python-testing)
  dc/python-testing deploys istag/python-testing:latest <-
    bc/python-testing source builds https://github.com/sclorg/django-ex.git#master on istag/python:3.9-minimal
      build #1 failed 9 minutes ago - 064993e: Mention the latest version in the main readme (Lumír 'Frenzy' Balhar <lbalhar@redhat.com>)
    deployment #1 waiting on image or update

Errors:
  * build/python-testing-1 has failed.
    try: Inspect the build failure with 'oc logs -f bc/python-testing'

Warnings:
  * The image trigger for dc/python-testing will have no effect until istag/python-testing:latest is imported or created by a build.

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

and finally `oc logs -f bc/python-testing`:
```bash
oc logs -f bc/python-testing
Cloning "https://github.com/sclorg/django-ex.git" ...
	Commit:	064993eb02b6feeeae1639f55fed127f98469051 (Mention the latest version in the main readme)
	Author:	Lumír 'Frenzy' Balhar <lbalhar@redhat.com>
	Date:	Fri Aug 20 09:26:53 2021 +0200
Caching blobs under "/var/cache/blobs".
Getting image source signatures
Copying blob sha256:d03aa1046a15856603a0ce459e2d87f9a0c076ed1aa438fd73cb12b2b073b8d3
Copying blob sha256:6e283f76f789b4f08aee986b1b358589ba2bb249263679d4c2849c239aa38368
Copying blob sha256:d9697ecd2a2882b0164a93db99e664186be8be46289271199c912ccfda10ea05
Copying blob sha256:1da51c2c627e98cf556d2dabe99f9543d969e71a1539d16bbf6da2061997ca60
Copying blob sha256:0791223bcd98a053b014d9a0e17af7545279b9040a0112da2cb3e5274d48bb51
Copying blob sha256:e4bfb219b2a60634d0617e06f3e0180c5703f777b8bfc6fd98df81a44a318014
Copying blob sha256:5eaf8832409f6caa1ddb923b24ff385c925562f040ef64da952edfe5aa9c8748
Copying config sha256:553222c101a81c85cef76a17a744366987ab6403d43dcb15a726e59e0444a347
Writing manifest to image destination
Storing signatures
Generating dockerfile with builder image image-registry.openshift-image-registry.svc:5000/sclorg-test-7656/python@sha256:330a81b829093b21fcdd177b757e12dcafb927b77ddcadcd606e00d6f3f8f8c1
Replaced Dockerfile FROM image image-registry.openshift-image-registry.svc:5000/sclorg-test-7656/python@sha256:330a81b829093b21fcdd177b757e12dcafb927b77ddcadcd606e00d6f3f8f8c1
STEP 1: FROM image-registry.openshift-image-registry.svc:5000/sclorg-test-7656/python@sha256:330a81b829093b21fcdd177b757e12dcafb927b77ddcadcd606e00d6f3f8f8c1 AS appimage023593412eca42d4a0fbb02a3d61a703
STEP 2: LABEL "io.openshift.build.image"="image-registry.openshift-image-registry.svc:5000/sclorg-test-7656/python@sha256:330a81b829093b21fcdd177b757e12dcafb927b77ddcadcd606e00d6f3f8f8c1"       "io.openshift.build.commit.author"="Lumír 'Frenzy' Balhar <lbalhar@redhat.com>"       "io.openshift.build.commit.date"="Fri Aug 20 09:26:53 2021 +0200"       "io.openshift.build.commit.id"="064993eb02b6feeeae1639f55fed127f98469051"       "io.openshift.build.commit.ref"="master"       "io.openshift.build.commit.message"="Mention the latest version in the main readme"       "io.openshift.build.source-location"="https://github.com/sclorg/django-ex.git"
STEP 3: ENV OPENSHIFT_BUILD_NAME="python-testing-1"     OPENSHIFT_BUILD_NAMESPACE="sclorg-test-7656"     OPENSHIFT_BUILD_SOURCE="https://github.com/sclorg/django-ex.git"     OPENSHIFT_BUILD_REFERENCE="master"     OPENSHIFT_BUILD_COMMIT="064993eb02b6feeeae1639f55fed127f98469051"     PIP_INDEX_URL=""
STEP 4: USER root
STEP 5: COPY upload/src /tmp/src
STEP 6: RUN chown -R 1001:0 /tmp/src
time="2022-01-25T10:44:38Z" level=warning msg="Path \"/run/secrets/etc-pki-entitlement\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
time="2022-01-25T10:44:38Z" level=warning msg="Path \"/run/secrets/redhat.repo\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
STEP 7: USER 1001
STEP 8: RUN /usr/libexec/s2i/assemble
time="2022-01-25T10:44:39Z" level=warning msg="Path \"/run/secrets/etc-pki-entitlement\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
time="2022-01-25T10:44:39Z" level=warning msg="Path \"/run/secrets/redhat.repo\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
---> Installing application source ...
---> Installing dependencies ...
Collecting django<1.12,>=1.11
  Downloading Django-1.11.29-py2.py3-none-any.whl (6.9 MB)
Collecting django-debug-toolbar==1.11.1
  Downloading django_debug_toolbar-1.11.1-py2.py3-none-any.whl (203 kB)
Collecting gunicorn==19.5.0
  Downloading gunicorn-19.5.0-py2.py3-none-any.whl (113 kB)
Collecting psycopg2-binary==2.8.5
  Downloading psycopg2-binary-2.8.5.tar.gz (381 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/app-root/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pmmhd4zx/psycopg2-binary_f9b25d0a048c40ebaff64913a2825f35/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pmmhd4zx/psycopg2-binary_f9b25d0a048c40ebaff64913a2825f35/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4qibloyd
         cwd: /tmp/pip-install-pmmhd4zx/psycopg2-binary_f9b25d0a048c40ebaff64913a2825f35/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-4qibloyd/psycopg2_binary.egg-info
    writing /tmp/pip-pip-egg-info-4qibloyd/psycopg2_binary.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-4qibloyd/psycopg2_binary.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-4qibloyd/psycopg2_binary.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-4qibloyd/psycopg2_binary.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/97/00/ed4c82364741031d745867f83820d4f373aa891098a5785841850491c9ba/psycopg2-binary-2.8.5.tar.gz#sha256=ccdc6a87f32b491129ada4b87a43b1895cf2c20fdb7f98ad979647506ffc41b6 (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement psycopg2-binary==2.8.5 (from versions: 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9, 2.9.1, 2.9.2, 2.9.3)
ERROR: No matching distribution found for psycopg2-binary==2.8.5
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/opt/app-root/bin/python3.9 -m pip install --upgrade pip' command.
STEP 9: FROM appimage023593412eca42d4a0fbb02a3d61a703
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": error while running runtime: exit status 1
```

@frenzymadness Thanks for your update, but it needs to be done also for `test/run-openshift-remote-cluster`.
I have already updated this PR.

**Comment by phracek** [comment]
I have checked locally if `RHEL8 - OpenShift 4` tests are passing and at least for `3.9-minimal` everything works fine.

[test-all]

**Comment by phracek** [comment]
@frenzymadness I have fixed finally all issues. Everything is GREEN.

**Comment by frenzymadness** [comment]
That's awesome, thank you. Could you please rebase/squash related commits together before we merge this PR?

**Comment by frenzymadness** [comment]
Not sure what happened to the OS 4 on RHEL 8. [test-openshift]

**Review by frenzymadness — APPROVED** [review]
All green! Awesome! Thanks a lot!

**Pull request merged**
