### PR TITLE
Drop pkg_prefix_dot, fix pkg_prefix and start using it

### PR DESCRIPTION
**Pull request by frenzymadness**
Resolves: #668

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
@hrnciar or @befeleme interested in the simple review?

**Comment by hrnciar** [comment]
+1, LGTM

**Comment by frenzymadness** [comment]
The latest release of uwsgi fixes one problem we have on RHEL 7 but brings another one which is hopefully fixed in the fixup release 2.0.25.1.

[test]

**Pull request merged**
