### PR TITLE
add link to ubi7 EULA

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
@frenzymadness @torsava PTAL

**Comment by frenzymadness** [comment]
PR https://github.com/sclorg/s2i-python-container/pull/327 has to be merged first and then this one rebased because now it contains unrelated changes in generated files.

**Comment by pkubatrh** [comment]
Rebased

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by frenzymadness** [comment]
Looks good to me. Thank you!

**Pull request merged**
