### PR TITLE
Add Fedora 41 - Python 3.13 container

### PR DESCRIPTION
**Pull request by befeleme**
Let's start with the testing




















































































































































































































































































































































<!-- testing-farm = {"lock":"false","comment-id":"2386104678","data":[{"id":"65630611-5532-4b82-898a-f8bd41845012","name":"Fedora - 3.12-minimal","status":"complete","outcome":"passed","runTime":1459.476286,"created":"2024-10-04T10:34:41.891519","updated":"2024-10-04T10:34:41.891526","compose":"Fedora-latest","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/65630611-5532-4b82-898a-f8bd41845012\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/65630611-5532-4b82-898a-f8bd41845012/pipeline.log\">pipeline</a>"]},{"id":"29d452c6-e733-4004-b9ce-3841aa31973e","name":"CentOS Stream 9 - 3.12-minimal","status":"complete","outcome":"passed","runTime":1384.688275,"created":"2024-10-04T10:34:41.746499","updated":"2024-10-04T10:34:41.746507","compose":"CentOS-Stream-9","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/29d452c6-e733-4004-b9ce-3841aa31973e\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/29d452c6-e733-4004-b9ce-3841aa31973e/pipeline.log\">pipeline</a>"]},{"id":"0d1d98b0-93bd-4616-8182-ee7a1f744749","name":"CentOS Stream 9 - 3.9-minimal","status":"complete","outcome":"passed","runTime":1379.184182,"created":"2024-10-04T10:35:32.676912","updated":"2024-10-04T10:35:32.676919","compose":"CentOS-Stream-9","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/0d1d98b0-93bd-4616-8182-ee7a1f744749\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/0d1d98b0-93bd-4616-8182-ee7a1f744749/pipeline.log\">pipeline</a>"]},{"id":"505ff3da-3101-46d9-9a04-0ed87d966d23","name":"CentOS Stream 9 - 3.11-minimal","status":"complete","outcome":"passed","runTime":1475.431288,"created":"2024-10-04T10:34:41.905465","updated":"2024-10-04T10:34:41.905474","compose":"CentOS-Stream-9","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/505ff3da-3101-46d9-9a04-0ed87d966d23\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/505ff3da-3101-46d9-9a04-0ed87d966d23/pipeline.log\">pipeline</a>"]},{"id":"481aa3ed-6c33-4979-9502-0216ae92307f","name":"CentOS Stream 9 - 3.11","status":"complete","outcome":"passed","runTime":1461.278129,"created":"2024-10-04T10:34:40.729038","updated":"2024-10-04T10:34:40.729044","compose":"CentOS-Stream-9","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/481aa3ed-6c33-4979-9502-0216ae92307f\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/481aa3ed-6c33-4979-9502-0216ae92307f/pipeline.log\">pipeline</a>"]},{"id":"aada47de-1682-4708-92ba-10a08a157472","name":"Fedora - 3.12","status":"complete","outcome":"passed","runTime":1422.786296,"created":"2024-10-04T10:34:44.270545","updated":"2024-10-04T10:34:44.270552","compose":"Fedora-latest","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/aada47de-1682-4708-92ba-10a08a157472\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/aada47de-1682-4708-92ba-10a08a157472/pipeline.log\">pipeline</a>"]},{"id":"3048d5eb-0a79-411b-843d-a477fa0ea585","name":"CentOS Stream 9 - 3.12","status":"complete","outcome":"passed","runTime":1452.11004,"created":"2024-10-04T10:34:40.883924","updated":"2024-10-04T10:34:40.883934","compose":"CentOS-Stream-9","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/3048d5eb-0a79-411b-843d-a477fa0ea585\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/3048d5eb-0a79-411b-843d-a477fa0ea585/pipeline.log\">pipeline</a>"]},{"id":"200d3cbe-9e36-4c9c-a063-27105e1e1345","name":"CentOS Stream 9 - 3.9","status":"complete","outcome":"passed","runTime":1384.37851,"created":"2024-10-04T10:35:23.865738","updated":"2024-10-04T10:35:23.865746","compose":"CentOS-Stream-9","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/200d3cbe-9e36-4c9c-a063-27105e1e1345\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/200d3cbe-9e36-4c9c-a063-27105e1e1345/pipeline.log\">pipeline</a>"]},{"id":"c55e9847-0619-4d41-932a-92f07e49e47b","name":"RHEL8 - 3.11-minimal","status":"complete","outcome":"passed","runTime":4968.815553,"created":"2024-10-04T10:34:48.207876","updated":"2024-10-04T10:34:48.207885","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/c55e9847-0619-4d41-932a-92f07e49e47b\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/c55e9847-0619-4d41-932a-92f07e49e47b/pipeline.log\">pipeline</a>"]},{"id":"64dfa84a-5e74-44ce-9c0f-5e01e466ff1a","name":"RHEL8 - 3.9-minimal","status":"complete","outcome":"passed","runTime":4258.819967,"created":"2024-10-04T10:46:37.439478","updated":"2024-10-04T10:46:37.439486","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/64dfa84a-5e74-44ce-9c0f-5e01e466ff1a\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/64dfa84a-5e74-44ce-9c0f-5e01e466ff1a/pipeline.log\">pipeline</a>"]},{"id":"0e712a84-980a-4f27-ad65-bcd63f27976d","name":"RHEL8 - 3.12-minimal","status":"complete","outcome":"passed","runTime":4758.159988,"created":"2024-10-04T10:34:43.262972","updated":"2024-10-04T10:34:43.262984","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/0e712a84-980a-4f27-ad65-bcd63f27976d\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/0e712a84-980a-4f27-ad65-bcd63f27976d/pipeline.log\">pipeline</a>"]},{"id":"4f5e5413-5e6e-421d-a522-28b123c63b83","name":"RHEL9 - 3.9","status":"complete","outcome":"passed","runTime":4185.900619,"created":"2024-10-04T10:35:00.830974","updated":"2024-10-04T10:35:00.830981","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/4f5e5413-5e6e-421d-a522-28b123c63b83\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/4f5e5413-5e6e-421d-a522-28b123c63b83/pipeline.log\">pipeline</a>"]},{"id":"84c3a8fc-fc99-4569-8488-695e457472dc","name":"RHEL9 - 3.12","status":"complete","outcome":"passed","runTime":4762.395988,"created":"2024-10-04T10:34:44.287660","updated":"2024-10-04T10:34:44.287667","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/84c3a8fc-fc99-4569-8488-695e457472dc\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/84c3a8fc-fc99-4569-8488-695e457472dc/pipeline.log\">pipeline</a>"]},{"id":"e18d75af-39b5-4c76-93cd-5c0537ba6d31","name":"RHEL8 - 3.11","status":"complete","outcome":"passed","runTime":5202.212273,"created":"2024-10-04T10:34:39.609646","updated":"2024-10-04T10:34:39.609657","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/e18d75af-39b5-4c76-93cd-5c0537ba6d31\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/e18d75af-39b5-4c76-93cd-5c0537ba6d31/pipeline.log\">pipeline</a>"]},{"id":"8636555a-1ac0-46b6-b408-fa0f52ffefac","name":"RHEL8 - 3.9","runTime":5146.839445,"created":"2024-10-04T10:35:25.582020","updated":"2024-10-04T10:35:25.582026","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"status":"complete","outcome":"passed","results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/8636555a-1ac0-46b6-b408-fa0f52ffefac\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/8636555a-1ac0-46b6-b408-fa0f52ffefac/pipeline.log\">pipeline</a>"]},{"id":"2c0cd4e2-87e4-4437-9f86-75cb77776e14","name":"RHEL9 - 3.11","status":"complete","outcome":"passed","runTime":4430.202546,"created":"2024-10-04T10:34:40.336606","updated":"2024-10-04T10:34:40.336615","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/2c0cd4e2-87e4-4437-9f86-75cb77776e14\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/2c0cd4e2-87e4-4437-9f86-75cb77776e14/pipeline.log\">pipeline</a>"]},{"id":"f8a9fa27-7bd5-46e3-b265-2d0bec9f35dd","name":"RHEL8 - 3.12","status":"complete","outcome":"passed","runTime":3706.526668,"created":"2024-10-04T10:34:41.984817","updated":"2024-10-04T10:34:41.984826","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/f8a9fa27-7bd5-46e3-b265-2d0bec9f35dd\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/f8a9fa27-7bd5-46e3-b265-2d0bec9f35dd/pipeline.log\">pipeline</a>"]},{"id":"d2520b5b-0d5b-4922-8d50-ff5a5c2129dc","name":"CentOS Stream 10 - 3.12-minimal","status":"complete","outcome":"passed","runTime":1030.861428,"created":"2024-10-04T10:34:40.570626","updated":"2024-10-04T10:34:40.570632","compose":"CentOS-Stream-10","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/d2520b5b-0d5b-4922-8d50-ff5a5c2129dc\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/d2520b5b-0d5b-4922-8d50-ff5a5c2129dc/pipeline.log\">pipeline</a>"]},{"id":"234a48b4-2f55-4684-8967-a52d5ae2f8b3","name":"CentOS Stream 10 - 3.12","status":"complete","outcome":"passed","runTime":1347.846449,"created":"2024-10-04T10:34:40.036742","updated":"2024-10-04T10:34:40.036750","compose":"CentOS-Stream-10","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/234a48b4-2f55-4684-8967-a52d5ae2f8b3\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/234a48b4-2f55-4684-8967-a52d5ae2f8b3/pipeline.log\">pipeline</a>"]},{"id":"69adfde8-a89e-4de4-835c-6e41611d7075","name":"Fedora - 3.13","status":"complete","outcome":"failed","runTime":1255.543185,"created":"2024-10-04T10:34:50.601627","updated":"2024-10-04T10:34:50.601634","compose":"Fedora-latest","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/69adfde8-a89e-4de4-835c-6e41611d7075\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/69adfde8-a89e-4de4-835c-6e41611d7075/pipeline.log\">pipeline</a>"]}]} -->

### CODE REVIEW

**Comment by befeleme** [comment]
[test]

**Comment by befeleme** [comment]
[test]

**Comment by befeleme** [comment]
[test]

**Comment by phracek** [comment]
Quay.io repositories for Python 3.13 and Python 3.13 minimal were created.
https://quay.io/repository/fedora/python-313
https://quay.io/repository/fedora/python-313-minimal

**Comment by befeleme** [comment]
`pyuwsgi-pipenv-test-app` - pyuwsgi doesn't publish wheels for Py 3.13 yet.
`test-fromdockerfile` needs psycopg2-binary, which doesn't have wheels for Py 3.13 yet.

The remaining two were hopefully fixed. 

[test]

**Review by frenzymadness — COMMENTED** [review]
There is only one micro nitpick I've found. The commits make sense to me and the content looks good. I consider two failing tests are acceptable and given the release schedule of Python 3.13, I think they'll be fixed soon.

**Comment by frenzymadness** [comment]
Perfect!

**Pull request merged**
