### PR TITLE
Python 3.11 on C8S

### PR DESCRIPTION
**Pull request by frenzymadness**
It will take a while until a new compose with Python 3.11 will be available so let's wait for it.

### CODE REVIEW

**Comment by zmiklank** [comment]
Could you please rebase this on master, so we could test the tfaga wrapper?

**Comment by frenzymadness** [comment]
Rebased. [ŧest]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
Nice.

**Comment by zmiklank** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
[test-openshift]

**Comment by frenzymadness** [comment]
Still no new C8S compose.

**Comment by frenzymadness** [comment]
[test]

**Comment by zmiklank** [comment]
Issue stays the same: `Error: Unable to find a match: python3.11-devel python3.11-pip`

**Comment by frenzymadness** [comment]
IIRC @torsava reported it somewhere.

**Comment by torsava** [comment]
> IIRC @torsava reported it somewhere.

Indeed: https://issues.redhat.com/browse/CS-1502

**Comment by frenzymadness** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
Well, lately it takes more time for github to assign job runners for us.

**Comment by frenzymadness** [comment]
All green. Let's merge it!

**Comment by frenzymadness** [comment]
And the new image is available: https://quay.io/repository/sclorg/python-311-c8s?tab=tags&tag=latest

**Pull request merged**
