### PR TITLE
Allow apps with setup.cfg without setup.py

### PR DESCRIPTION
**Pull request by frenzymadness**
Fixes: #479

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test]

**Comment by dperaza4dustbit** [comment]
OK, thanks for pointing us here @gabemontero I will follow up with @frenzymadness on slack

**Comment by frenzymadness** [comment]
I'm not able to test it now. Could you please provide some logs? As far as I know, there might be some issues currently caused by the latest release of pipenv.

**Comment by dperaza4dustbit** [comment]
OK, going to work on disabling the test on origins first, and then will work with you @frenzymadness on slack to get you some logs.

**Pull request merged**
