### PR TITLE
Fedora 38 is EOL

### PR DESCRIPTION
**Pull request by befeleme**
This is changed on top of #708

### CODE REVIEW

**Comment by befeleme** [comment]
[test]

**Comment by befeleme** [comment]
[test]

**Comment by befeleme** [comment]
[test]

**Comment by befeleme** [comment]
[test]

**Review by phracek — CHANGES_REQUESTED** [review]
Can you please remove also obsoleted Dockerfiles in https://github.com/sclorg/s2i-python-container/blob/master/.github/workflows/build-and-push.yml#L57

**Comment by befeleme** [comment]
> Can you please remove also obsoleted Dockerfiles in https://github.com/sclorg/s2i-python-container/blob/master/.github/workflows/build-and-push.yml#L57

I don't see any obsolete Dockerfiles here - we still build 3.11-minimal with Centos Stream 9

**Comment by frenzymadness** [comment]
> > Can you please remove also obsoleted Dockerfiles in https://github.com/sclorg/s2i-python-container/blob/master/.github/workflows/build-and-push.yml#L57
> 
> I don't see any obsolete Dockerfiles here - we still build 3.11-minimal with Centos Stream 9

Petr was right but he pointed to an incorrect line. The file build-and-push.yml contains definitions for 3.11 and 3.11-minimal on Fedora that should be removed as well.

**Comment by befeleme** [comment]
:woman_facepalming: I found it and removed the mentions from the CI config file and README.

**Review by frenzymadness — APPROVED** [review]
Thank you!

**Pull request merged**
