### PR TITLE
Add templates from openshift/origin.

### PR DESCRIPTION
**Pull request by pvalena**
~~WIP, because I'm not sure whether to use json or yaml.~~

### CODE REVIEW

**Comment by torsava** [comment]
[test]

**Comment by torsava** [comment]
Thanks, @pvalena, for working on this!

What do you think about documenting this for the users? Maybe a README file inside the examples directory?

**Comment by pvalena** [comment]
@torsava, the idea is to align with mariadb-container folders [test](https://github.com/sclorg/mariadb-container/tree/master/test) and [examples](https://github.com/sclorg/mariadb-container/tree/master/examples) for now. We are to maintain the [templates](https://github.com/sclorg/mariadb-container/pull/48#issuecomment-334615187) and, therefore, we have to test them too.

That said, feel free to propose any README file and I can create pull requests for the rest of containers.
Please also look into the CI tests' failures, as I'm quite sure my changes did not cause them.

**Comment by torsava** [comment]
Tests are passing, merging.

**Pull request merged**
