### PR TITLE
Add aarch64 imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by hhorak** [comment]
This PR would need a rebase, as it does not include the recent changes in the imagestreams. I've created #401 instead for simplified review.

**Pull request closed without merging**
