### PR TITLE
Add virtualenv and UPGRADE_PIP_TO_LATEST tests

### PR DESCRIPTION
**Pull request by torsava**
I've taken a look at issue #177 and tried to come up with a way to test the virtual env and UPGRADE_PIP_TO_LATEST functionality.

Due to the way the tests are handled in s2i, they needs to be made into a test-app that will then be able to respond to HTML requests. That part of the test would be useless for testing the above mentioned and thus I opted for bundling the test with an already existing test-app. What do you think?

### CODE REVIEW

**Comment by torsava** [comment]
@pkubatrh @GrahamDumpleton Could you please take a look?

**Comment by pkubatrh** [comment]
Seems reasonable. Could you add the test case changes to other python versions as well?

**Comment by torsava** [comment]
@pkubatrh Thanks for looking into it! I've amended the commits to test all the three active versions.

**Comment by pkubatrh** [comment]
Thanks, merging.

**Pull request merged**
