### PR TITLE
Add Integration tests to be run in a remote cluster

### PR DESCRIPTION
**Pull request by hhorak**
The idea is to have an easy way to run tests in an existing cluster, that might be remote via `make test-openshift-remote-cluster` or directly via `test/run-openshift-remote-cluster`.

### CODE REVIEW

**Comment by hhorak** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test] [test-openshift]

**Comment by pkubatrh** [comment]
@hhorak Symlink to test-lib-openshift.sh missing from versioned directories:
```
test/run-openshift: line 13: test/test-lib-python.sh: No such file or directory
```

**Comment by pkubatrh** [comment]
For 2.7 that is

**Comment by pkubatrh** [comment]
I expect you will also need to add the symlinks to:
https://github.com/sclorg/s2i-python-container/blob/master/manifest.sh

**Comment by frenzymadness** [comment]
Can I help here somehow?

**Comment by frenzymadness** [comment]
Is this still valid?

**Comment by hhorak** [comment]
The aim to have tests that run with remote cluster is definitely valid, as OCP 4.x does not support `oc cluster up` thing that was used to test the containers on OCP 3.x. Thanks for reminding, this needs more focus now than before.

**Comment by frenzymadness** [comment]
Does the #381 implement the same? Can we close this one?

**Comment by hhorak** [comment]
> Does the #381 implement the same? Can we close this one?

Yes, closing this one.

**Pull request closed without merging**
