### PR TITLE
Fedora 32 has reached EOL

### PR DESCRIPTION
**Pull request by frenzymadness**
SSIA

### CODE REVIEW

**Comment by frenzymadness** [comment]
@phracek Could you please take a look at why the test results seem to be truncated/incomplete?

**Comment by frenzymadness** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by frenzymadness** [comment]
My plan is to merge this PR because the change for Fedora should definitely not have any impact on RHEL.

The issues I see in the CI:
- RHEL7:
  - Tests for rhscl/python-27-rhel7:2.7 succeeded.
  - Tests for python-38 failed on a timeout when pipenv was locking and downloading info from PyPI
  - For some reason, the output is not complete. The last test is the test from Dockerfile with no s2i scripts used
- RHEL8:
  - Tests for ubi8/python-27:2.7 succeeded.
  - Tests for ubi8/python-36:1 succeeded.
  - Tests for ubi8/python-38:1 succeeded.
  - And again, the output is not complete. I don't know why.

**Pull request merged**
