### PR TITLE
Reorder imagestreams

### PR DESCRIPTION
**Pull request by phracek**
This commit only reorder imagestream.
First is the latest tag and second is the latest version

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
In reference to PR, why this change is needed https://github.com/sclorg/ansible-tests/pull/4

**Comment by phracek** [comment]
@torsava @frenzymadness Can you please look at it? The PR itself only moves the latest version right after the latest tag. Nothing to more complicated.

**Comment by torsava** [comment]
@phracek I did take a look already. The changes indeed reorder the imagestreams. +1

**Comment by torsava** [comment]
@phracek Should Python 3.8 be added as the first entry, when it's available for all platforms?

**Comment by phracek** [comment]
@torsava If it is already available for RHEL and CentOS, then yes. But images itself are not available in registry yet.

@pkubatrh What do you think?

**Comment by torsava** [comment]
> @torsava If it is already available for RHEL and CentOS, then yes. But images itself are not available in registry yet.

Oh absolutely, I'm not saying you should delay the PR to wait. Just asking whether this needs to be done later. +1

**Comment by frenzymadness** [comment]
Looks good to me, thank you!

**Pull request merged**
