### PR TITLE
Set defaults for lang/locale and I/O encoding.

### PR DESCRIPTION
**Pull request by GrahamDumpleton**
This addresses issues raised in #156 whereby various Python web applications and modules might assume that a default locale off UTF-8 is used. If such an application or module is used on OpenShift it will fail. It is not necessarily realistic to expect that people will be able to fix their code to handle bytes/unicode encoding correctly and so sensible defaults should be used.

To do this three environment variables should be set. These are ``LANG``, ``LC_ALL`` and ``PYTHONIOENCODING``.

Technically you might be able to get away with ``LANG`` and not ``LC_ALL`` for Python applications as Python will look for both when initialising. It is though safer to set both as the behaviour of separate non Python applications executed from the web application may not be as tolerant and so require both to handle different situations.

The ``PYTHONIOENCODING`` is also needed to ensure that when a terminal is not associated with the running application, which is default for application run from ``CMD``, or where an application is run and input/output passes through a pipe, that a suitable encoding is also set otherwise it will fallback to ASCII for Python 2 applications. Python 3 applications will possibly fallback to UTF-8, but better to set it regardless of Python version to be consistent.

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test]

**Comment by hhorak** [comment]
The RHEL7 test fails with "Network timed out while trying to connect to https://index.docker.io/v1/repositories/rhscl/s2i-base-rhel7/images. You may want to check your internet connection or if you are behind a proxy." I guess it is some temporary random issue only.

**Comment by pkubatrh** [comment]
>The RHEL7 test fails with "Network timed out while trying to connect to https://index.docker.io/v1/repositories/rhscl/s2i-base-rhel7/images. You may want to check your internet connection or if you are behind a proxy." I guess it is some temporary random issue only.

Actually failing because of:
Get https://registry.access.redhat.com/v2/rhscl/s2i-base-rhel7/manifests/latest: net/http: TLS handshake timeout

Still seems like a temporary issue so will try re-running tests later

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
RHEL7 tests failing because of:

File "/opt/app-root/src/wsgi.py", line 11, in hello
    assert os.environ['LC_ALL'] == 'en_US.UTF-8'
AssertionError

Looking at the log this might be the cause:
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_AU.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_AU.UTF-8)

Running the tests manually on a rhel 7.3 virtual machine didn't fail on me.

**Comment by pkubatrh** [comment]
[test]

**Comment by pvalena** [comment]
@hhorak, I do not know of any Ruby application that could be broken by different LANG/LC_ALL setting. And when some Ruby app does break, I think it should be fixed in the app itself (i.e. not hard-coded).
I do not think there is any use-case for this in case of Ruby :)

**Comment by hhorak** [comment]
Since there is no feedback that such change would be beneficial in other languages, let's do it in Python for now. We can change this decision and move it to s2i-base any time later.

@GrahamDumpleton can you, please, rebase?

**Comment by hhorak** [comment]
@GrahamDumpleton #159 changed same piece, one more rebase is needed.

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
I've tried github feature and it seems I was able to resolve the conflicts instead of you, let's see whether the tests still pass.

**Pull request merged**
