### PR TITLE
Add test_latest_imagestreams

### PR DESCRIPTION
**Pull request by phracek**
Add test_latest_imagestreams

### CODE REVIEW

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
RHEL7 test is failing because cluster does not start properly:
```bash
I1113 04:52:40.814419   18817 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1113 04:52:46.795651   18817 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

OpenShift tests for rhscl/python-38-rhel7:1 failed.
```

**Comment by phracek** [comment]
All OpenShift 4 tests are PASSING.

**Comment by zmiklank** [comment]
Could you please elaborate more on the "fixing django_ex repo template versions" part?
I can not see it in the code, only in commit message.

**Comment by phracek** [comment]
> Could you please elaborate more on the "fixing django_ex repo template versions" part? I can not see it in the code, only in commit message.

It is not directly in this repo. It is in django-ex repo. It is mentioned in commit message

**Comment by zmiklank** [comment]
> > Could you please elaborate more on the "fixing django_ex repo template versions" part? I can not see it in the code, only in commit message.
> 
> It is not directly in this repo. It is in django-ex repo. It is mentioned in commit message

The thing I do not understand is how the code in this PR affects the django-ex, or its template versions.

**Comment by phracek** [comment]
[test-openshift]

**Comment by frenzymadness** [comment]
When it comes to OpenShift, you know well what you do so feel free to merge this when you are happy with the outcome.

**Comment by phracek** [comment]
RHEL7 OpenShift 3 fails because the cluster does not start up properly:

```bash
Starting OpenShift using registry.redhat.io/openshift3/ose-control-plane:v3.11 ...
I1115 05:08:35.052609   18819 config.go:40] Running "create-master-config"
I1115 05:08:38.855050   18819 config.go:46] Running "create-node-config"
I1115 05:08:39.849869   18819 flags.go:30] Running "create-kubelet-flags"
I1115 05:08:40.277235   18819 run_kubelet.go:49] Running "start-kubelet"
I1115 05:08:40.480761   18819 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1115 05:09:21.494483   18819 interface.go:26] Installing "kube-proxy" ...
I1115 05:09:21.495224   18819 interface.go:26] Installing "kube-dns" ...
I1115 05:09:21.495238   18819 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1115 05:09:21.495249   18819 interface.go:26] Installing "openshift-apiserver" ...
I1115 05:09:21.495256   18819 apply_template.go:81] Installing "kube-proxy"
I1115 05:09:21.495283   18819 apply_template.go:81] Installing "openshift-apiserver"
I1115 05:09:21.495479   18819 apply_template.go:81] Installing "kube-dns"
I1115 05:09:21.496641   18819 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1115 05:09:27.076561   18819 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

OpenShift tests for rhscl/python-38-rhel7:1 failed.
errexit on line 63, common/test.sh
```

**Pull request merged**
