### PR TITLE
Add first tests for OpenShift use cases

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by hhorak** [comment]
[test-openshift]

**Comment by hhorak** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
Similarly to the httpd PR, `THISDIR` and `IMAGE_NAME` need to be quoted.

**Comment by hhorak** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test]

**Comment by omron93** [comment]
LGTM, thanks.

**Pull request merged**
