### PR TITLE
Remove Python 2 and the rest of EL 7

### PR DESCRIPTION
**Pull request by frenzymadness**

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test-all]

**Comment by frenzymadness** [comment]
@phracek 

```
/usr/bin/python3: No module named pytest
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Test for image ubi9/python-311:1 FAILED in these versions  3.11.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
make: *** [common/common.mk:116: test-openshift-pytest] Error 1
```

My guess: If you want to use Python 3.12 and python3.12-pytest, you have to call python3.12 explicitly, not just python3.

**Comment by frenzymadness** [comment]
Ping @hrnciar and @phracek

**Comment by hrnciar** [comment]
I eyeballed the changes, they are mostly removals. LGTM

**Review by hrnciar — APPROVED** [review]

**Comment by frenzymadness** [comment]
@phracek could you please confirm that the failures in the CI are expected now?

**Comment by phracek** [comment]
Well the problem with pytest was fixed by PR https://github.com/sclorg/s2i-python-container/pull/694.

**Comment by phracek** [comment]
[test]

**Review by phracek — APPROVED** [review]
LGTM. Thanks for this issue.

**Pull request merged**
