### PR TITLE
Introduce version 3.6 - rebased

### PR DESCRIPTION
**Pull request by chrisburr**
This PR is simply #208 rebased to fix the conflicts with an additional commit to address the comments of @torsava.

If you would rather close this and rebase/merge #208 instead I am be happy with that, I just did this as I needed to build an image using Python 3.6.

### CODE REVIEW

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by torsava** [comment]
Looks good to me, thanks @chrisburr! Unless there are any objections, I'll merge this.

**Comment by pkubatrh** [comment]
@chrisburr Please add the 3.6 version string into the Makefile over at:
https://github.com/chrisburr/s2i-python-container/blob/introduce-36-rebase/Makefile#L3

If this is not set the CI tests are not run against the new version (and having `.exclude-rhel7` is pointless in that case).

**Comment by pkubatrh** [comment]
Also needs a rebase before being able to be merged

**Comment by chrisburr** [comment]
@pkubatrh Done

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
Seems like the 3.6 scl rpms are already in `centos-sclo-rh-testing`. @chrisburr please also remove this line to make the CentOS tests pass:
https://github.com/chrisburr/s2i-python-container/blob/introduce-36-rebase/3.6/Dockerfile#L37

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
Tests are green now, thanks! LGTM.

**Pull request merged**
