### PR TITLE
add imagestreams to image repo

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@praiskup @hhorak @pkubatrh @pvalena ptal

**Comment by pkubatrh** [comment]
@bparees Is it necessary to keep the deprecated images in the imagestream as well?

**Comment by pkubatrh** [comment]
Will merge for now since it does not matter much anyway but it would be good to know whether we can remove them in future without causing harm.

**Comment by bparees** [comment]
> @bparees Is it necessary to keep the deprecated images in the imagestream as well?

yes for backwards compatibility we need to keep deprecated images in the imagestream, but we tag them as "hidden"

**Pull request merged**
