### PR TITLE
Checking if tests pass on RHEL8

### PR DESCRIPTION
**Pull request by torsava**

### CODE REVIEW

**Comment by torsava** [comment]
[test]

**Comment by torsava** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test]

**Comment by frenzymadness** [comment]
It seems that RHEL8 is okay and I am working on a fix for Centos/RHEL with Python 2.7 and numpy described in #341 .

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
RHEL8 seems to be okay and RHEL/Centos 7 are fixed in PR #342 .

**Pull request closed without merging**
