### PR TITLE
Allow to run only one test separately by specifying as an argument

### PR DESCRIPTION
**Pull request by hhorak**
This is just a small enhancement to make the debugging faster.

### CODE REVIEW

**Comment by frenzymadness** [comment]
Well, it looks simple but I had to take a proper look at this :) It looks good to me and makes sense. Have you tried it with optional arguments? I guess that the standard case without an optional argument is tested by our CI.

**Comment by hhorak** [comment]
> Have you tried it with optional arguments?

I'm not sure I follow -- which arguments do you mean?

**Comment by frenzymadness** [comment]
> > Have you tried it with optional arguments?
> 
> I'm not sure I follow -- which arguments do you mean?

When you try it with only one test so only the test you give to the script (as an argument) is executed..

**Comment by frenzymadness** [comment]
Could you please note how can I use this new possibility?

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
I have tried to find out explanation about `${@:-${WEB_APPS[@]}}` what `@:-` should do, but no chance.

The output looks the same as before. I would like to understand this improvement.

My test was:
```bash
$ declare -a WEB_APPS=({test1,test2-foo,test3-bar}-webn)
$ for u in ${@:-${WEB_APPS[@]}}; do echo ${u}; done
test1-webn
test2-foo-webn
test3-bar-webn
$
```

**Comment by pkubatrh** [comment]
>I would like to understand this improvement.

`$@` is a list of quoted arguments to the script, `${@:-$value}` checks if any arguments are provided and uses `$value` as the default if there are none. In this case `${WEB_APPS[@]}` is used which is a list of test cases

**Comment by phracek** [comment]
I see, then if `test/run` is executed with the arguments, then they are used for testing the app
otherwise, the default set is used.

**Comment by phracek** [comment]
I would be glad for any kind of note, how can it be used in real time?

**Comment by hhorak** [comment]
I've rebased this for newest master and added a comment how to use this. Let me know if it's not clear.

**Comment by phracek** [comment]
@frenzymadness What do you think now?

**Pull request merged**
