### PR TITLE
Fix nodejs scl version

### PR DESCRIPTION
**Pull request by frenzymadness**
The variable is defined in the s2i-base image.

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
LGTM. Thanks for fixing.

**Comment by phracek** [comment]
Let's try it one more.

[test]

**Comment by phracek** [comment]
`CentOS7-openshift` failed because of OpenShift does not start properly.

```bash
08:45:10 Pulled 3/5 layers, 69% complete
08:45:10 Pulled 4/5 layers, 97% complete
08:45:12 Pulled 5/5 layers, 100% complete
08:45:12 Extracting
08:45:12 Image pull complete
08:45:28 Pulling image openshift/origin-cli:v3.11
08:45:28 E0430 07:45:28.770183   23899 helper.go:179] Reading docker config from /root/.docker/config.json failed: open /root/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11 anonymously
08:45:28 error: error pulling Docker image openshift/origin-cli:v3.11
08:45:28 error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:
08:45:29 
08:45:29   1. Via the command-line flag --config
08:45:29   2. Via the KUBECONFIG environment variable
08:45:29   3. In your home directory as ~/.kube/config
08:45:29 

```

**Comment by frenzymadness** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
`SCLorg-CI for rhel7 - openshift` failed because of OpenShift does not start properly.


```bash
I0430 16:47:08.068976    9664 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0430 16:47:20.089831    9664 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:
  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config
To view or setup config directly use the 'config' command.
OpenShift tests for rhscl/python-27-rhel7:2.7 failed.
```

**Comment by phracek** [comment]
[test-openshift]

**Comment by frenzymadness** [comment]
[test-openshift]

**Pull request merged**
