### PR TITLE
Fix pip version for python 2 in tests

### PR DESCRIPTION
**Pull request by frenzymadness**
pip 21 does not support python 2 anymore

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test] [test-openshift]

**Comment by frenzymadness** [comment]
There seems to be an unrelated problem in OpenShift. @phracek could you please take a look?

@torsava review of this change appreciated although it's only about tests.

**Comment by torsava** [comment]
> @torsava review of this change appreciated although it's only about tests.

@frenzymadness It's a good change for python27, absolutely. But I'm worried that adding it also to python38/python39 README files is very confusing. When I would be reading the README I would be asking myself why do I have to use an old version of pip.

**Comment by frenzymadness** [comment]
> @frenzymadness It's a good change for python27, absolutely. But I'm worried that adding it also to python38/python39 README files is very confusing. When I would be reading the README I would be asking myself why do I have to use an old version of pip.

You are right. I'm gonna try to fix it. It'd require to switch from a symlink to the dockerfile to a full copy of the file generated by the distgen to have a different version for Python 2 and Python 3 but it'll mean that we actually test the exact same version we have in readmes so it's worth it.

**Comment by frenzymadness** [comment]
[test] [test-openshift]

**Comment by frenzymadness** [comment]
Fixed!

* test/from-dockerfile (folder) is no longer a symlink
* test/from-dockerfile/Dockerfile.tpl is now a symlink (simply because it's the same for all versions)
* test/from-dockerfile/Dockerfile_no_s2i.tpl is now generated via distgen to have exactly the same content as the readme

**Review by torsava — APPROVED** [review]
Very nice solution. LGTM!

**Comment by frenzymadness** [comment]
Thanks!

**Pull request merged**
