### PR TITLE
Add support for testing imagestreams on RHEL9 in OpenShift 4

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
Fedora and RHEL8 - 3.9-minimal tests have issue here: https://github.com/sclorg/s2i-python-container/issues/552

**Review by frenzymadness — APPROVED** [review]
I think that the diff is okay and it seems that the OS 4 tests for RHEL 9 succeeded.

**Pull request merged**
