### PR TITLE
use local reference policy for tags

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by omron93** [comment]
[test]

**Comment by bparees** [comment]
ci failure seems unrelated to this change

**Comment by omron93** [comment]
You are right.
@hroncok @torsava Please, could you take a look? Newer pipenv is being installed, so the failure is probably somehow connected...

**Comment by hroncok** [comment]
> Please, could you take a look?

On what? I'm not following this discussion, sorry.

**Comment by omron93** [comment]
> On what? I'm not following this discussion, sorry.

Oh, sorry:-( It should be @mcyprian instead...

**Comment by hroncok** [comment]
No problem :) Edited. Clutter removed.

**Comment by mcyprian** [comment]
I am looking into it.

**Pull request merged**
