### PR TITLE
Document npm purpose and no guarantee for version

### PR DESCRIPTION
**Pull request by hhorak**
SSIA

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test]

**Comment by mcyprian** [comment]
We use to divide all changes into two separate commits since we use distgen for this repo. First we commit changes of templates/sources under /src directory and than we commit regenerated directories for Python versions. This is not a hard requirement just a note.

**Comment by mcyprian** [comment]
LGTM otherwise.

**Comment by hhorak** [comment]
I'll divide it, that makes sense. (sorry my ignorance, this is my first commit to dist-gen-ed repo :)

**Comment by hhorak** [comment]
Tests fail now due infra, but passed previously, so merging.

**Comment by omron93** [comment]
>We use to divide all changes into two separate commits since we use distgen for this repo. First we commit changes of templates/sources under /src directory and than we commit regenerated directories for Python versions. This is not a hard requirement just a note.

@mcyprian Do you plan to remove generated sources? Like postgresql-container did - it keeps generated sources in automatically updated `generated` branch.

**Comment by mcyprian** [comment]
@omron93 We definitely plan to do so. We've decided to commit sources for a while to make the switch to distgen smooth.

We are not  sure what is the right way to make the generated sources diff visible. The goal is not to make the work of PR reviewer unnecessarily difficult. As soon as there is some good solution to handle these kind of things in postgresql-container, we will be happy to switch to this model as well. **FYI** @torsava

**Comment by torsava** [comment]
@omron93 As Michal said, we'd like the diff of the generated sources be visible during a PR. And the easiest way to do that is to have the generated sources be part of this repo.

However, perhaps it would be possible to have some bot that automatically regenerates the sources for every PR and links to a diff? We could work together on such a mechanism, as it would be useful for all distgen-based repos.

**Pull request merged**
