### PR TITLE
using a tmp dir for the passwd file

### LINKED ISSUE #298: generate_container_user can not create `/opt/app-root/etc/passwd`
at https://github.com/sclorg/s2i-python-container/blob/9e911631f49ca5de59260c882c0b6ff5c5ad3ee8/3.6/root/opt/app-root/etc/generate_container_user#L7 the container tries to create a passwd file for the nss_wrapper. See also #98 

Why is this created in `/opt/app-root/etc/passwd` rather than /tmp? Logs I see indicate that the file could not be written:

```
/opt/app-root/etc/generate_container_user: line 10: /opt/app-root/etc/passwd: Permission denied
/opt/app-root/etc/generate_container_user: line 12: /opt/app-root/etc/passwd: Permission denied
```

### PR DESCRIPTION
**Pull request by goern**
Fixed #298 

Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Comment by goern** [comment]
@rhscl-bot @centos-ci thanks for the help!

**Comment by omron93** [comment]
[test][test-openshift]

**Comment by goern** [comment]
#298 seems not be related to this change, merge if you like it or close the PR! Thanks!

**Comment by omron93** [comment]
@torsava ?

**Pull request merged**
