### PR TITLE
Update imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by frenzymadness** [comment]
The diff looks good to me. Is there any way how to test it?

**Comment by yselkowitz** [comment]
AFAIK only within the context of OpenShift, which should happen after this is merged here, automatically synced into openshift/library, then imported from there into the cluster-samples-operator.

**Comment by frenzymadness** [comment]
And are you able to do it after I merge this PR?

**Comment by yselkowitz** [comment]
No, I'm not set up for that.  How do you normally deal with imagestreams updates?

**Comment by yselkowitz** [comment]
To clarify, I did make sure that these changes will import and verify in the openshift library.

**Comment by frenzymadness** [comment]
Okay, let's test this. Thank you!

**Pull request merged**
