### PR TITLE
Add Python 3.11 and Fedora 37 + some small updates

### PR DESCRIPTION
**Pull request by frenzymadness**

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test-all]

**Comment by frenzymadness** [comment]
[test-all]

**Comment by frenzymadness** [comment]
@zmiklank Could you please take a look at the changes I've made in `.github/`? Are those enough to test and publish the new container image?

**Comment by zmiklank** [comment]
Yes, I think the changes are sufficient.

**Comment by frenzymadness** [comment]
> Yes, I think the changes are sufficient.

Thanks for the quick reply but I don't see the tests for Python 3.11 running here.

**Comment by zmiklank** [comment]
Stuff from `.github/workflows/` are in the PR being taken from master branch, not from PR branch. You can first merge only these changes separately and then continue your work at this PR.

**Comment by zmiklank** [comment]
It should be also stated in the `contribution.md`, but it is not. I will add it there eventually.

**Comment by frenzymadness** [comment]
> Stuff from `.github/workflows/` are in the PR being taken from master branch, not from PR branch. You can first merge only these changes separately and then continue your work at this PR.

If I do that. What will happen in the master branch where 3.11 does not exist? Will the actions just ignore non-existing images/folders/combinations?

**Comment by zmiklank** [comment]
The actions (either build-and-push and test action) will fail on Python 3.11 target. Other targets should not be affected by it.

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
[test]

**Pull request merged**
