### PR TITLE
openshift: Test both sclorg and origin templates

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by omron93** [comment]
@pkubatrh Please update common/ - it should fix RHEL7-openshift CI.

**Comment by pkubatrh** [comment]
Rebased, thanks for info!

[test-openshift]

**Comment by pkubatrh** [comment]
The fedora failure looks like some virtualenv issue

@torsava Can you take a look?
https://ci.centos.org/job/SCLo-container-python-rh-fedora/50/console

**Comment by torsava** [comment]
@pkubatrh Apologies, I'm currently swamped with a different project. How urgent is this?

**Comment by pkubatrh** [comment]
@torsava Not urgent at all, can definitely wait for when you have more time.

**Comment by omron93** [comment]
[test][test-openshift]

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Comment by frenzymadness** [comment]
I'd like to finish this but unfortunately, I don't understand what this change is intended to do. Could you please explain it to me?

**Comment by pkubatrh** [comment]
@frenzymadness Sure!
There are two sets of Openshift templates - ones that live in the sclorg/django-ex repository and ones that live in Origin (Openshift upstream) library (copied from sclorg/django-ex periodically).
Currently we are only testing changes against sclorg/django-ex templates but it would make more sense to test against both so that we know we do not break something in the templates that are currently being used in Openshift.

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
[test-openshift]

**Comment by frenzymadness** [comment]
The change itself looks good to me but it might need to be rebased to make CI happy.

**Comment by pkubatrh** [comment]
Rebased, lets try once more.

[test-openshift]

**Comment by pkubatrh** [comment]
rhel7 and rhel8 test runs missing due to some issues with CI, will follow up

**Comment by pkubatrh** [comment]
CI fixed now, rel8 failing because of #360

**Comment by frenzymadness** [comment]
Good job, thank you.

**Pull request merged**
