### PR TITLE
Python 3.6 is EOL for RHEL-7

### PR DESCRIPTION
**Pull request by phracek**
Python 3.6 is EOL for RHEL-7.
Disabling builds.

Also, container-common-scripts are updated

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
@frenzymadness I would be glad for a review. RHEL8 is supported but RHEL-7 is EOL.

**Comment by phracek** [comment]
I am not sure about CentOS? Do we want to deprecate it as well?

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
>I am not sure about CentOS? Do we want to deprecate it as well?

Yes, Centos7 deprecation is tied to RHSCL EOL dates

**Comment by phracek** [comment]
Let's try with tests.

[test][test-openshift]

**Comment by phracek** [comment]
@frenzymadness Can you please look at this PR?
What do you think? Are there any changes needed? Especially from the dist-gen point of view?

[test]

**Review by frenzymadness — CHANGES_REQUESTED** [review]
This repository does not use `*/.exclude-*` files. Instead of them, you should extend the matrix in `multispec.yml`. In the end, the distgen will stop generating the Docker files at all.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Test again.

[test]

**Review by frenzymadness — APPROVED** [review]
The code looks good to me and we can temporarily ignore the RHEL 8 CI until podman is fixed there. Thank you!

**Pull request merged**
