### PR TITLE
[DO NOT MERGE] Add dummy file for testing CI

### PR DESCRIPTION
**Pull request by fila43**

### CODE REVIEW

**Comment by fila43** [comment]
[test]

**Comment by fila43** [comment]
[test-openshift]

**Comment by frenzymadness** [comment]
Is this PR still useful?

**Comment by fila43** [comment]
It's not necessary, but every time when we need to test CI process we can just make a rebase and test.

**Comment by frenzymadness** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Pull request closed without merging**
