### PR TITLE
New release of Build-and-push action with suffix support

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Review by zmiklank — CHANGES_REQUESTED** [review]
3.9-minimal has the following inconsistency:
 ```     
            tag: "el8"
            suffix: "c9s"
```

**Comment by phracek** [comment]
[test-all]

**Comment by frenzymadness** [comment]
Are the failed jobs related to this change? Do you plan to address the inconsistency spotted by Zuzka?

**Comment by zmiklank** [comment]
@frenzymadness all build-and-push jobs are failing because of this one.
(e.g., https://github.com/sclorg/s2i-python-container/actions/runs/2267483949)
If you have testing jobs in mind - they should not be affected by this specific bug.

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test]

**Review by zmiklank — APPROVED** [review]
I have fixed the inconsistency.

**Pull request merged**
