### PR TITLE
Remove streams that will be soon EOL.

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by hhorak** [comment]
[test-openshift]

**Comment by hhorak** [comment]
@yselkowitz @phracek @pkubatrh WDYT?

**Comment by yselkowitz** [comment]
Besides the fact that it seems a bit odd to EOL rh-python36 when python3 is supported in RHEL7 for the rest of its life, LGTM, but any explanation for the test failures?

**Comment by yselkowitz** [comment]
Mentions of 3.6-ubi7 as an option in django-ex should also be removed -- even better if it can be moved to 3.8 instead.

**Comment by hhorak** [comment]
> Besides the fact that it seems a bit odd to EOL rh-python36 when python3 is supported in RHEL7 for the rest of its life

Yeah, it might seem odd, but those are two different stacks, with different use cases and reasons for inclusion; they only have one common thing, the same python version.

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by hhorak** [comment]
We still didn't convince Jenkins to work properly, so I verified manually that the imagestream is valid. Merging.

**Pull request merged**
