### PR TITLE
Add Python 3.12 and 3.12-minimal with C10S

### PR DESCRIPTION
**Pull request by befeleme**
- enchant and atlas-devel are no longer available in the distribution - removed them for now but without knowing what they were responsible for, I can't really tell if that's enough or we should find a replacement.

### CODE REVIEW

**Comment by frenzymadness** [comment]
Atlas is for linear algebra (scientific applications) and enchant is an abstraction for spell-checking. Will see what will happen without them. I don't think we have a test or an internal functionalities requiring those two so we should be fine.

**Comment by befeleme** [comment]
`micropipenv-requirements-test-app` failed with the traceback:

```
Wed Sep 11 10:58:34.578491 2024] [wsgi:error] [pid 9:tid 9] mod_wsgi (pid=9): Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:8080:100001/handler.wsgi'.
[Wed Sep 11 10:58:34.579949 2024] [wsgi:error] [pid 9:tid 9] Traceback (most recent call last):
[Wed Sep 11 10:58:34.580312 2024] [wsgi:error] [pid 9:tid 9]   File "/tmp/mod_wsgi-localhost:8080:100001/handler.wsgi", line 90, in <module>
[Wed Sep 11 10:58:34.580454 2024] [wsgi:error] [pid 9:tid 9]     handler = mod_wsgi.server.ApplicationHandler(entry_point,
[Wed Sep 11 10:58:34.580603 2024] [wsgi:error] [pid 9:tid 9]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Sep 11 10:58:34.580736 2024] [wsgi:error] [pid 9:tid 9]   File "/opt/app-root/lib64/python3.12/site-packages/mod_wsgi/server/__init__.py", line 1457, in __init__
[Wed Sep 11 10:58:34.580883 2024] [wsgi:error] [pid 9:tid 9]     __import__(entry_point)
[Wed Sep 11 10:58:34.581017 2024] [wsgi:error] [pid 9:tid 9]   File "/opt/app-root/src/wsgi.py", line 1, in <module>
[Wed Sep 11 10:58:34.581156 2024] [wsgi:error] [pid 9:tid 9]     import enchant
[Wed Sep 11 10:58:34.581297 2024] [wsgi:error] [pid 9:tid 9]   File "/opt/app-root/lib64/python3.12/site-packages/enchant/__init__.py", line 81, in <module>
[Wed Sep 11 10:58:34.581431 2024] [wsgi:error] [pid 9:tid 9]     from enchant import _enchant as _e
[Wed Sep 11 10:58:34.581602 2024] [wsgi:error] [pid 9:tid 9]   File "/opt/app-root/lib64/python3.12/site-packages/enchant/_enchant.py", line 157, in <module>
[Wed Sep 11 10:58:34.581610 2024] [wsgi:error] [pid 9:tid 9]     raise ImportError(msg)
[Wed Sep 11 10:58:34.581629 2024] [wsgi:error] [pid 9:tid 9] ImportError: The 'enchant' C library was not found and maybe needs to be installed.
[Wed Sep 11 10:58:34.581633 2024] [wsgi:error] [pid 9:tid 9] See  https://pyenchant.github.io/pyenchant/install.html
[Wed Sep 11 10:58:34.581635 2024] [wsgi:error] [pid 9:tid 9] for details
```

I checked the test, it just imports enchant, doesn't really do anything with it. So let's just remove it and see what happens.

[test]

**Comment by befeleme** [comment]
Now the tests run successfully. Can we drop enchant like that? Since the C library is no longer available in the distro, whoever needs it, will have to find another way.

**Comment by phracek** [comment]
Thanks for this Pull request. You do GREAT jobs. Or maybe better say AWESOME job/

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Waw. We are GREEN. Good job. Please review it.

**Review by phracek — APPROVED** [review]
LGTM. The tests are GREEN

**Comment by hrnciar** [comment]
+1, LGTM

**Pull request merged**
