### PR TITLE
replaces nss_wrapper with nss_wrapper-libs

### PR DESCRIPTION
**Pull request by phracek**
This pull request replaces nss_wrapper with nss_wrapper-libs

Less dependency and unnecessary footprint

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Review by befeleme — CHANGES_REQUESTED** [review]
Would you also like to change the `Dockerfile-minimal.template`? `nss_wrapper` is hardcoded there and given it's minimal, we probably want to make the footprint smaller there too.

**Comment by phracek** [comment]
I forgot to replace nss-wrapper with nss-wrapper-libs for minimal images.
This fix it https://github.com/sclorg/s2i-python-container/pull/713/commits/da66a0932bc1f0dab1741cef85a4398d29cbffd3

[test]

**Comment by phracek** [comment]
The was an Ethel (subscription manager outage), it should be fixed now.

[test]

**Comment by phracek** [comment]
RHEL9 - 3.9 has passed:
```
10:37:27                 out: 
10:37:27                 out:  [PASSED] for 'gunicorn-config-different-port-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'gunicorn-config-different-port-test-app' test_s2i_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'gunicorn-config-different-port-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'gunicorn-config-different-port-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'gunicorn-config-different-port-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'gunicorn-config-different-port-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'gunicorn-different-port-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'gunicorn-different-port-test-app' test_s2i_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'gunicorn-different-port-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'gunicorn-different-port-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'gunicorn-different-port-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'gunicorn-different-port-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'django-different-port-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'django-different-port-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'django-different-port-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'django-different-port-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'django-different-port-test-app' test_application_with_user (00:00:05)
10:37:27                 out:  [PASSED] for 'django-different-port-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'standalone-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'standalone-test-app' test_s2i_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'standalone-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'standalone-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'standalone-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'standalone-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'setup-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'setup-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'setup-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'setup-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'setup-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'setup-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'setup-requirements-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'setup-requirements-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'setup-requirements-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'setup-requirements-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'setup-requirements-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'setup-requirements-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'django-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'django-test-app' test_s2i_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'django-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'django-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'django-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'django-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'numpy-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'numpy-test-app' test_s2i_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'numpy-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'numpy-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'numpy-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'numpy-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'app-home-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'app-home-test-app' test_s2i_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'app-home-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'app-home-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'app-home-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'app-home-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'locale-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'locale-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'locale-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'locale-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'locale-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'locale-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'pipenv-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'pipenv-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'pipenv-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'pipenv-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'pipenv-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'pipenv-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'pipenv-and-micropipenv-should-fail-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'app-module-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'app-module-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'app-module-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'app-module-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'app-module-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'app-module-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'pyuwsgi-pipenv-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'pyuwsgi-pipenv-test-app' test_s2i_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'pyuwsgi-pipenv-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'pyuwsgi-pipenv-test-app' test_application (00:00:05)
10:37:27                 out:  [PASSED] for 'pyuwsgi-pipenv-test-app' test_application_with_user (00:00:05)
10:37:27                 out:  [PASSED] for 'pyuwsgi-pipenv-test-app' test_application_enable_init_wrapper (00:00:05)
10:37:27                 out:  [PASSED] for 'micropipenv-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'micropipenv-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'micropipenv-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'micropipenv-test-app' test_application (00:00:07)
10:37:27                 out:  [PASSED] for 'micropipenv-test-app' test_application_with_user (00:00:07)
10:37:27                 out:  [PASSED] for 'micropipenv-test-app' test_application_enable_init_wrapper (00:00:07)
10:37:27                 out:  [PASSED] for 'standalone-custom-pypi-index-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'standalone-custom-pypi-index-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'standalone-custom-pypi-index-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'standalone-custom-pypi-index-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'standalone-custom-pypi-index-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'standalone-custom-pypi-index-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'gunicorn-python-configfile-different-port-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'gunicorn-python-configfile-different-port-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'gunicorn-python-configfile-different-port-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'gunicorn-python-configfile-different-port-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'gunicorn-python-configfile-different-port-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'gunicorn-python-configfile-different-port-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'setup-cfg-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'setup-cfg-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'setup-cfg-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'setup-cfg-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'setup-cfg-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'setup-cfg-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'npm-virtualenv-uwsgi-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'npm-virtualenv-uwsgi-test-app' test_s2i_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'npm-virtualenv-uwsgi-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'npm-virtualenv-uwsgi-test-app' test_application (00:00:06)
10:37:27                 out:  [PASSED] for 'npm-virtualenv-uwsgi-test-app' test_application_with_user (00:00:06)
10:37:27                 out:  [PASSED] for 'npm-virtualenv-uwsgi-test-app' test_application_enable_init_wrapper (00:00:07)
10:37:27                 out:  [PASSED] for 'mod-wsgi-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'mod-wsgi-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'mod-wsgi-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'mod-wsgi-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'mod-wsgi-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'mod-wsgi-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'pin-pipenv-version-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'pin-pipenv-version-test-app' test_s2i_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'pin-pipenv-version-test-app' test_docker_run_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'pin-pipenv-version-test-app' test_application (00:00:05)
10:37:27                 out:  [PASSED] for 'pin-pipenv-version-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'pin-pipenv-version-test-app' test_application_enable_init_wrapper (00:00:05)
10:37:27                 out:  [PASSED] for 'micropipenv-requirements-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'micropipenv-requirements-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'micropipenv-requirements-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'micropipenv-requirements-test-app' test_application (00:00:05)
10:37:27                 out:  [PASSED] for 'micropipenv-requirements-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'micropipenv-requirements-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'poetry-src-layout-test-app' run_s2i_build ()
10:37:27                 out:  [PASSED] for 'poetry-src-layout-test-app' test_s2i_usage (00:00:01)
10:37:27                 out:  [PASSED] for 'poetry-src-layout-test-app' test_docker_run_usage (00:00:00)
10:37:27                 out:  [PASSED] for 'poetry-src-layout-test-app' test_application (00:00:04)
10:37:27                 out:  [PASSED] for 'poetry-src-layout-test-app' test_application_with_user (00:00:04)
10:37:27                 out:  [PASSED] for 'poetry-src-layout-test-app' test_application_enable_init_wrapper (00:00:04)
10:37:27                 out:  [PASSED] for 'var-docker' test_scl_variables_in_dockerfile (00:00:00)
10:37:27                 out:  [PASSED] for 'var-docker' test_from_dockerfile (00:00:43)
```

**Comment by phracek** [comment]
So we are ready to MERGE.

**Pull request merged**
