### PR TITLE
remove generate-new target, as it is now duplicate of 'make generate'

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by frenzymadness** [comment]
Thank you! I'm gonna use this PR to check the current status of the CI. It can be merged anytime. [test-all]

**Comment by frenzymadness** [comment]
@zmiklank it's okay for you if I add some commits here to try to fix the CI?

**Comment by zmiklank** [comment]
@frenzymadness, sure.

**Comment by frenzymadness** [comment]
[test-all]

**Comment by frenzymadness** [comment]
[test-all]

**Comment by frenzymadness** [comment]
@zmiklank I expect the CI to be mostly green this time [test-all]

Except for the failures of CentOS 7 - 3.8 and CentOS7 - Openshift 3 - 3.8 – they don't seem to be a problem in the container image, the error I've found in the log says `Pipeline reported an exception in module 'test-schedule-runner': Failure during Ansible playbook execution`. Is this something known and ignorable here?

**Comment by zmiklank** [comment]
Unfortunately is centos7 compose broken on Testing Farm's side [1].

So please ignore it.

[1] https://issues.redhat.com/browse/TFT-1577

**Comment by frenzymadness** [comment]
Thank you. If the rest of the test jobs will be okay, I'll merge it.

**Comment by phracek** [comment]
Thank you very much for solving this issue and #552

**Pull request merged**
