### PR TITLE
Pip from wheel

### PR DESCRIPTION
**Pull request by frenzymadness**
Follow up for #412 - needs to be rebased after #440 to make centos-openshift CI job green.

It can also wait for a while because the pip wheel is from the new Fedora 34 and it's therefore kinda fresh.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
rebase please.

**Comment by phracek** [comment]
RHEL-7 test failed on 
```bash
 Value /opt/rh/rh-nodejs14/root/usr/share/man is missing from variable MANPATH
MANPATH=/opt/rh/rh-python27/root/usr/share/man:/opt/rh/python27/root/usr/share/man:/opt/rh/httpd24/root/usr/share/man:/opt/rh/rh-nodejs10/root/usr/share/man

```

It was solved by #440 . Rebase it and tests should pass.

**Comment by frenzymadness** [comment]
[test][test-openshift] Rebased

**Comment by phracek** [comment]
`CentOS7 - openshift` failure should be solved soon by https://github.com/sclorg/container-common-scripts/issues/195

**Comment by frenzymadness** [comment]
> `CentOS7 - openshift` failure should be solved soon by [sclorg/container-common-scripts#195](https://github.com/sclorg/container-common-scripts/issues/195)

Cool. This is a kinda big change so I'm gonna wait and we can use this PR to test the fix for openshift.

**Comment by frenzymadness** [comment]
I'm gonna rebase this PR and once more update the wheel.

**Comment by frenzymadness** [comment]
[test][test-openshift][test-openshift-4]

**Comment by frenzymadness** [comment]
[test][test-openshift][test-openshift-4]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by frenzymadness** [comment]
One last rebase and I'm going to either merge this or I'll investigate CI more.

**Comment by frenzymadness** [comment]
[test][test-openshift][test-openshift-4]

**Comment by frenzymadness** [comment]
So far in the CI:
- RHEL7:
  - Tests for rhscl/python-27-rhel7:2.7 succeeded.
  - All tests for rhscl/python-38-rhel7:1 passed except locale-test-app which failed on timeout when communicating with PyPI
- tests on OpenShift 3 are broken entirely now.

**Comment by frenzymadness** [comment]
The rest of the CI is finally green so I'm gonna merge this now.

**Pull request merged**
