### PR TITLE
Add support of pipenv packaging tool

### PR DESCRIPTION
**Pull request by mcyprian**
Pipenv, the higher-level Python packaging tool can be used to manage application dependencies 
if user requests it by setting ENABLE_PIPENV environment variable to true. Pipenv and its dependecies
are sandboxed so they cannot conflict with neither system packages nor application dependencies.
This PR contains:
- support of pipenv in assemble script
- simple test application using Pipfile
- update of relevant parts of documentation

### CODE REVIEW

**Comment by omron93** [comment]
[test]

**Comment by mcyprian** [comment]
[test]

**Comment by bkabrda** [comment]
So I did a line-by-line review of this PR and I don't see any potential issues; the implementation is clean and everything seems to work as documented. Nice job and 👍 from me!

**Comment by mcyprian** [comment]
Thanks @bkabrda.

**Pull request merged**
