### PR TITLE
Implement very simple shell init wrapper

### PR DESCRIPTION
**Pull request by frenzymadness**
Init wrapper is important for proper signal handling and zombie processes reaping. See issues mentioned below for more details.

Based on https://github.com/sclorg/s2i-python-container/pull/233 . Fixes https://github.com/sclorg/s2i-python-container/issues/94 and https://github.com/sclorg/s2i-python-container/issues/93

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test-openshift]

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
@torsava interested in a review?
@GrahamDumpleton, could you please take a look? You have probably the longest experience with the simple init wrapper.

**Comment by torsava** [comment]
Reviewing (gotta reread all the threads).

@frenzymadness It'd be nice to have a test for this as well, but I'm not sure it's worth the time. What do you think?

**Comment by torsava** [comment]
@frenzymadness Next time it would be more readable to separate the commits into the source changes, and then the regenerated files.

**Comment by torsava** [comment]
@pkubatrh @praiskup Do you know of any other s2i containers that already do this?

**Comment by frenzymadness** [comment]
Comments:
* The change is now in two commits
* I don't think I am able to write some test for these issues. It would require:
    * Implement a new test application which can create zombie processes and check that they are reaped properly
    * Use existing django test application to test signal handling where you have to use some timeout mechanism to check whether it is really killed by signal from outside or the timeout itself.
* Suggested changes applied

**Comment by praiskup** [comment]
> Do you know of any other s2i containers that already do this?

I don't.

**Comment by torsava** [comment]
[test-openshift]

**Comment by torsava** [comment]
Everything looks top notch now!
Let's see the tests and then merge this.

Thanks, @frenzymadness!

**Comment by frenzymadness** [comment]
I think that we are ready to merge this :)

**Comment by torsava** [comment]
Indeed, merging!

**Pull request merged**
