### PR TITLE
Sync downstream changes

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by omron93** [comment]
What about adding `rpm-file-permissions` into last `RUN` statement?

**Comment by pkubatrh** [comment]
>What about adding rpm-file-permissions into last RUN statement?

Makes sense, must have missed it while adding downstream. Thanks!

**Comment by pkubatrh** [comment]
Modified the RUN command so that it does not introduce another layer.

**Comment by omron93** [comment]
Tests are passing. So merging.

**Pull request merged**
