### PR TITLE
Add NPM support and tests

### PR DESCRIPTION
**Pull request by torsava**
In light of the [recent addition of npm to s2i-base-container](https://github.com/sclorg/s2i-base-container/pull/132), I've enabled npm in this image and added some tests for it as well.

What do you think, @omron93, @pkubatrh, @hhorak ?

WIP because I'd like to wait for some feedback before committing to the other Python versions as well.

### CODE REVIEW

**Comment by omron93** [comment]
@torsava I don't see any problem, thanks.

Only there are some problems with yum in rhel7.4, so please add this workaround (https://github.com/sclorg/mongodb-container/pull/253/commits/40322ebd4b61b7a1039a07581a9517eb6c406056) to let RHEL CI pass.

**Comment by hhorak** [comment]
Sounds good to me. There is one more thing though -- the s2i base image with nodejs is not yet released, so the testing might fail even after fixing the 7.4 work-around. I'd probably go with it and merge it anyway, since waiting for next rebuild doesn't seem worth the PASS sign.

**Comment by torsava** [comment]
I've propagated the changes to all active versions and added the rhel7.4 workaround, thanks @omron93 !

However, the RHEL build now fails with `error: option --user not recognized`, which seems like some problem with the build machinery. Would anyone know what that might be?

**Comment by pkubatrh** [comment]
>However, the RHEL build now fails with error: option --user not recognized, which seems like some problem with the build machinery. Would anyone know what that might be?

This looks like some issue with the jenkins builder (my PRs are hitting this all across the board) so @omron93 might know more.

**Comment by pkubatrh** [comment]
@torsava Likely a side-effect of https://github.com/sclorg/container-common-scripts/commit/55d1108ed56058756665e5fe893c1e07f73bdce7. Rebasing to latest `common` seems to have fixed the issue in my PRs.

**Comment by torsava** [comment]
Thank you @pkubatrh, it indeed helped. Now the RHEL test fails due to rh-nodejs6 not being available in the s2i-base-container as @hhorak predicted.

**Comment by torsava** [comment]
Rebased onto the master so there are no conflicts.

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
@torsava There are new conflicts now, please, rebase.

**Comment by torsava** [comment]
@hhorak Rebased.

**Pull request merged**
