### PR TITLE
use newest build-and-push action

### PR DESCRIPTION
**Pull request by zmiklank**
Main change is, that the distgen will no longer be called before build of the image.

### CODE REVIEW

**Comment by frenzymadness** [comment]
IIRC the distgen is not called before build here in Python container image. That's the reason why the new generator does not fail for Python in https://github.com/sclorg/container-common-scripts/pull/294

**Comment by zmiklank** [comment]
@frenzymadness 

This is part of a different workflow; Unfortunately in build-and-push action was distgen called independently from common's Makefiles. See https://github.com/sclorg/build-and-push-action/commit/034c7fb9d6a72318794921c5ddf197e4518624d6.

**Comment by frenzymadness** [comment]
You are right, thanks for the context. I trust you here so feel free to merge this as you wish.

**Comment by zmiklank** [comment]
Ok, lets see :).

**Comment by zmiklank** [comment]
It seems to work.

**Pull request merged**
