### PR TITLE
generate imagestream files with imagestream generator.

### PR DESCRIPTION
**Pull request by zmiklank**
Generator is here: https://github.com/sclorg/ci-scripts/tree/master/ocp-stream-generator

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-openshift]

**Comment by phracek** [comment]
RHEL 9 - OpenShift 4 - 3.12 should be fixed by https://github.com/sclorg/s2i-python-container/pull/683

**Comment by phracek** [comment]
@zmiklank Please rebase it against master.

**Comment by zmiklank** [comment]
> @zmiklank Please rebase it against master.

Rebased. Also I think the latest imagestreams are incorrect here. Could you please re-check?

**Comment by zmiklank** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
@phracek, it seems that tmt plan is failing.

**Comment by phracek** [comment]
@zmiklank I will investigate. It looks like downloading by curl  from gitlab.cee.redhat.com was changed.

**Comment by phracek** [comment]
Let's try it one more time 

[test]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
OpenShift 4 failures are expected. Our Cluster is not available.

**Review by phracek — APPROVED** [review]
LGTM

**Pull request merged**
