### PR TITLE
Use Testing Farm as GitHub Action also for OpenShift tests

### PR DESCRIPTION
**Pull request by phracek**
This pull request simplifies testing s2i-python-container in OpenShift tests.

Testing Farm as GitHub action is used for it.
Similar to https://github.com/sclorg/s2i-python-container/pull/506

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
Fedora tests can failed because of #507

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by frenzymadness** [comment]
I don't understand all the bells and whistles here but I believe you. On the other hand, a lot of tests failed. Do we want to merge #507 first and test this again after a rebase?

**Comment by phracek** [comment]
> I don't understand all the bells and whistles here but I believe you. On the other hand, a lot of tests failed. Do we want to merge #507 first and test this again after a rebase?

Yes please, #507 has to be merged before this one.

**Comment by phracek** [comment]
[test-all]

**Pull request merged**
