### PR TITLE
Make npm-virtualenv-uwsgi-test-app compatible with mkdirp 3.0.0

### PR DESCRIPTION
**Pull request by frenzymadness**
mkdirp 3.0.0 has no default exports any more
https://github.com/isaacs/node-mkdirp/blob/main/CHANGELOG.md#30

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
@befeleme This might be a good candidate for the first review if you are interested. No worries about failing RHEL CI, it's a known issue.

**Comment by befeleme** [comment]
Thank you, I'll take a look at it.

**Comment by frenzymadness** [comment]
TF should be okay now, restarting [test]

**Review by befeleme — APPROVED** [review]
I verified that there was an error running the `mkdirp` package and this change indeed fixes it. Apart from running the example applications on my machine I learned something about JS today. :) Thanks and LGTM!

**Pull request merged**
