### PR TITLE
Fix x scl name

### PR DESCRIPTION
**Pull request by phracek**
This pull request fixes a typo in Dockerfile.rhel7.

Collection `rh-python27` does not exists. But python27 yes.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Review by frenzymadness — CHANGES_REQUESTED** [review]
You should run distgen when you change source files. However, the failure in the tests is caused by something else and I know what is the cause, I'll investigate it tomorrow.

**Comment by phracek** [comment]
[test]

> You should run distgen when you change source files. However, the failure in the tests is caused by something else and I know what is the cause, I'll investigate it tomorrow.

The second commit is after dist-gen generated sources ;) The only `2.7/Dockerfile.rhel7` was changed. Which is true.

**Comment by frenzymadness** [comment]
> The second commit is after dist-gen generated sources ;) The only `2.7/Dockerfile.rhel7` was changed. Which is true.

As far as I see in my local copy of this PR, distgen also regenerates `2.7/Dockerfile` for Centos 7. Or do I misunderstand something?

**Comment by frenzymadness** [comment]
Could you please rebase this PR to fix the CI and then run make clean-versions && make generate-all?

**Comment by frenzymadness** [comment]
BTW I see that this is already fixed downstream. At least for python 2 container,

**Comment by phracek** [comment]
The downstream already contains a fix. I have rebased and regenerated content.
But for some reason these Dockerfiles are missing:

```bash
2.7/Dockerfile
3.8/Dockerfile
3.8/Dockerfile.fedora
3.9/Dockerfile.fedora
```

**Comment by phracek** [comment]
[test]

**Review by frenzymadness — CHANGES_REQUESTED** [review]
There must be something wrong in your setup or somewhere else. The change you have made to `src/Dockerfile.template` should be reflected in `2.7/Dockerfile.rhel7` and `2.7/Dockerfile` but your commit with generated files contains only the first mentioned file.
When I check out this PR and run `make clean-versions && make generate-all` I see the uncommited change in the Dockerfile for Centos in 2.7 folder.

**Comment by phracek** [comment]
[test]

**Review by frenzymadness — APPROVED** [review]
Thank you!

**Pull request merged**
