### PR TITLE
move test_latest_imagestreams case into openshift tests

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by phracek** [comment]
LGTM. As soon as tests are green we can merge it :)

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
Tests are green. Hurray. Merging ;)

**Pull request merged**
