### PR TITLE
 Generate actual test files instead of symlinks 

### PR DESCRIPTION
**Pull request by pkubatrh**
Resolves: #272

### CODE REVIEW

**Comment by pkubatrh** [comment]
@torsava Can you take a look if the change is ok with you?

imo it is no longer necessary to symlink everything now that we are using source generation.

**Comment by torsava** [comment]
@pkubatrh Sorry it took me a while to get to this.

Copying the files instead of symlinking solves the immediate issue, but it heavily pollutes the regenerated diffs, so I'd like to avoid it if possible.

I've tried to track down the source of the issue, and it seems it's a bug in `common/generate.sh`. If you delete all variants (2.7, 3.5, 3.6) it generates fine. If you delete only some variants, it adds the cyclic symlinks, because the symlinks are already there, so it adds them into the symlinked directory, causing the issue.

I don't have too much time to dig into this at the moment to go dig into common scripts. How critical is this, should we merge this as a (maybe) temporary workaround?

**Comment by pkubatrh** [comment]
Not critical at all, just a pita since I need to work around the issue during the sync with github content.

I did not try to dig into the code to find the issue behind this since I felt it would be better to get rid of symlinks entirely now that we have code generation but as you say the secondary use-case of not polluting diffs is still there.

**Comment by pkubatrh** [comment]
We decided off-line some time ago to not go with generating all of the sources with distgen yet.

Additionally #272 has been fixed through https://github.com/sclorg/container-common-scripts/pull/98

Closing for now.

**Pull request closed without merging**
