### PR TITLE
Fedora update - drop Py 3.10 on F36 and update Py 3.11 to F38

### PR DESCRIPTION
**Pull request by frenzymadness**
SSIA Cc @befeleme

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test]

**Review by befeleme — APPROVED** [review]
The changes look good to me.

**Comment by befeleme** [comment]
Suggestion - there are those lines in the README - change to 37/38?

```
Fedora versions currently supported are:
* Fedora 36 ([quay.io/fedora](https://quay.io/organization/fedora))
* Fedora 37 ([quay.io/fedora](https://quay.io/organization/fedora))
```

**Comment by frenzymadness** [comment]
> Suggestion - there are those lines in the README - change to 37/38?

Good catch! F37 is no longer needed as we have only Python 3.11 on F38.

Rebased on top of your PR.

**Comment by frenzymadness** [comment]
[test]

**Review by befeleme — APPROVED** [review]
I went through the update, this time LGTM without remarks.

**Pull request merged**
