### PR TITLE
Update README.md (3.6) – note regarding npm

### PR DESCRIPTION
**Pull request by isbur**
reference to base image where npm is actually included

### CODE REVIEW

**Comment by frenzymadness** [comment]
Looks good to me but why is this only in 3.6/readme instead of src/readme and regenerated for all?

**Comment by phracek** [comment]
@isbur Can you please update this PR as we suggest?

**Comment by frenzymadness** [comment]
Let me know if you need any help. If you don't want to finish this, I can do it.

**Comment by frenzymadness** [comment]
Replaced by #364

**Pull request closed without merging**
