### PR TITLE
Fedora 33 and Python 3.9

### PR DESCRIPTION
**Pull request by frenzymadness**
New Fedora release and a new Python version. Both are not yet stable.

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test-openshift]

**Comment by frenzymadness** [comment]
CI looks good. This si now ready for a review. I'd like to ship it when Python 3.9.0 final will be available in repos.

**Comment by frenzymadness** [comment]
Python 3.9.0 is ready in the repositories.

[test]

**Review by torsava — APPROVED** [review]
That looks good, ship it! :)

**Pull request merged**
