### PR TITLE
Move common parts out from this project

### PR DESCRIPTION
**Pull request by omron93**
Common parts used for building are shared in https://github.com/sclorg/container-common-scripts and added as git submodule.

Similar PR discussed in https://github.com/sclorg/postgresql-container/pull/138

@hhorak @bparees @pkubath Please take a look.

### CODE REVIEW

**Comment by omron93** [comment]
Changes in build scripts:
```
--- s2i-python-container/hack/build.sh	2017-04-25 12:17:03.722318977 +0200
+++ container-common-scripts/build.sh	2017-04-25 12:16:53.804265620 +0200
@@ -34,3 +34,3 @@
   cp ${DOCKERFILE_PATH} "${DOCKERFILE_PATH}.version"
-  git_version=$(git rev-parse HEAD)
+  git_version=$(git rev-parse --short HEAD)
   echo "LABEL io.openshift.builder-version=\"${git_version}\"" >> "${dockerfile}.version"
@@ -68,2 +68,4 @@
         NAMESPACE="centos/"
+      elif [ "${OS}" == "fedora" ]; then
+        NAMESPACE="fedora/"
       else
@@ -89,2 +91,4 @@
     docker_build_with_version Dockerfile.rhel7
+  elif [ "$OS" == "fedora" -o "$OS" == "fedora-candidate" ]; then
+    docker_build_with_version Dockerfile.fedora
   else
@@ -94,3 +98,3 @@
   if [[ -v TEST_MODE ]]; then
-    IMAGE_NAME=${IMAGE_NAME} test/run
+    VERSION=$dir IMAGE_NAME=${IMAGE_NAME} test/run
 
@@ -102,2 +106,11 @@
 
+  if [[ -v TEST_OPENSHIFT_MODE ]]; then
+    if [[ -x test/run-openshift ]]; then
+      VERSION=$dir IMAGE_NAME=${IMAGE_NAME} test/run-openshift
+    else
+      echo "-> OpenShift tests are not present, skipping"
+    fi
+  fi
+
+
   popd > /dev/null
```

```
--- s2i-python-container/hack/common.mk	2017-04-25 12:17:03.722318977 +0200
+++ container-common-scripts/common.mk	2017-04-25 10:41:50.514630470 +0200
@@ -2,3 +2,7 @@
 
-build = hack/build.sh
+ifndef common_dir
+    common_dir = common
+endif
+
+build = $(common_dir)/build.sh
 
@@ -6,2 +10,4 @@
 	OS := rhel7
+else ifeq ($(TARGET),fedora)
+	OS := fedora
 else
@@ -26 +32,5 @@
 	$(script_env) TAG_ON_SUCCESS=$(TAG_ON_SUCCESS) TEST_MODE=true $(build)
+
+.PHONY: test-openshift
+test-openshift:
+	$(script_env) TAG_ON_SUCCESS=$(TAG_ON_SUCCESS) TEST_OPENSHIFT_MODE=true $(build)
```

New functionality:
- allow to build also fedora based images
- allow to run OpenShift tests if implemented (https://github.com/sclorg/mongodb-container/blob/master/3.2/test/run-openshift)

Changes:
- `git_version=$(git rev-parse HEAD)` vs `git_version=$(git rev-parse --short HEAD)`. It is not clean now. 11 sclorg images uses short revision for `io.openshift.builder-version` label, rest (6 images) uses long revision. @bparees Are there any hard requirements why to choose any way?

@hhorak @bparees Please take a look.

**Comment by pkubatrh** [comment]
looks ok

**Comment by bparees** [comment]
>  @bparees Are there any hard requirements why to choose any way?

no requirements, no.  short revision ought to be sufficient.

**Comment by hhorak** [comment]
Looks ok to me as well, merging.

**Pull request merged**
