### PR TITLE
Python 3.12 for C8S and C9S

### PR DESCRIPTION
**Pull request by frenzymadness**

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test]

**Comment by zmiklank** [comment]
Hello, thanks for PR. Do we want to publish this images on quay.io?

If yes, would you please update [build-and-push action](https://github.com/sclorg/s2i-python-container/blob/master/.github/workflows/build-and-push.yml) accordingly? And I can create new quay.io repositories.

**Comment by frenzymadness** [comment]
The problem on RHEL 7 is already reported upstream for uwsgi.

> Hello, thanks for PR. Do we want to publish this images on quay.io?

Yes, will do, thanks for the reminder.

**Comment by frenzymadness** [comment]
[test-all]

**Comment by zmiklank** [comment]
> Yes, will do, thanks for the reminder.

Thanks. Also the repositories are ready to be used now :).

**Comment by frenzymadness** [comment]
@hrnciar Take a look at the individual commits here and I'll explain their meaning later.

**Comment by frenzymadness** [comment]
[test]

**Comment by hrnciar** [comment]
+1, LGTM

**Review by zmiklank — APPROVED** [review]

**Pull request merged**
