### PR TITLE
Use SCL httpd24 packages instead of operating system httpd package.

### PR DESCRIPTION
**Pull request by GrahamDumpleton**
As per #161 use httpd24 packages from Software Collections Library instead of the operating system httpd package.

This becomes important for corporate customers who need to integrate their Python WSGI applications into an SSO infrastructure. By using the SCL httpd24 package, along with either mod_ldap, mod_auth_kerb or mod_session, also installed from SCL in this change, they can when using mod_wsgi-express use the authentication and authorisation handlers of Apache httpd server, backed by the providers in these modules to implement their SSO solution.

This enables them to use a supported SSO mechanism and they do not need to implement a custom SSO solution within their own Python WSGI application.

These changes were tested on CentOS for Python 2.7, 3.3, 3.4 and 3.5 using the application:

* https://gitlab.com/osevg/python-flask-modwsgi

For example, using new versions of modules:

```
oc new-app python:2.7~https://gitlab.com/osevg/python-flask-modwsgi --name app27
```

This validated that mod_wsgi-express correctly found the Apache installation at build time and could compile itself, with it then starting successfully when deployed.

The test didn't check the operation of mod_ldap, mod_auth_kerb or mod_session as these were pulled from SCL and it is expected that are complete and will work when required.

Testing of RHEL variants of images not done at this point, however changes are still made to the RHEL versions of the Dockerfile for each Python version.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@GrahamDumpleton, thanks for the PR :+1:

@hhorak could you please assign this to the current maintainer(s)?

@bparees FYI

I don't know if I can trigger [test] here, can I?

**Comment by GrahamDumpleton** [comment]
Have now added specific tests using mod_wsgi-express so get automated testing for all images using this WSGI server configuration.

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
RHEL7 tests failing because of what seems to be a network issue. Will try re-running tests later.

**Comment by hhorak** [comment]
[test]

**Comment by torsava** [comment]
The code looks good, I've tried testing it, and it all looks good to me. I don't have merging power, however.

**Comment by hhorak** [comment]
Looks good to me as well, although the explaining text from PR would be great for a commit message. 
@GrahamDumpleton, can you rebase, please, and possibly squash or at least alter the commit message?
(I know it took a bit longer to review, sorry)

**Comment by GrahamDumpleton** [comment]
[test]

**Comment by GrahamDumpleton** [comment]
[test]

**Comment by GrahamDumpleton** [comment]
[test]

**Comment by GrahamDumpleton** [comment]
Is there a reason I can never seem to get tests to be run? Same on other PR about unbuffered output.

**Comment by rhcarvalho** [comment]
@GrahamDumpleton I believe there's a whitelist. I can try for you, [test]

**Comment by GrahamDumpleton** [comment]
I cant get access RHEL7 Jenkins instance. Not sure if I would have a login or not. So can't see what error is.

**Comment by pkubatrh** [comment]
RHEL7 tests are failing because of this test case:

23:12:32 [1m[INFO] Building the mod-wsgi-test-app application image ...[0m
23:12:52 E0321 19:12:51.073883 07510 main.go:352] An error occurred: timeout after waiting 20s for Docker to create container
23:12:52 [1m[INFO] TEST FAILED (1)[0m`

**Comment by GrahamDumpleton** [comment]
That looks like a transient issue. Can someone trigger the test again.

**Comment by pkubatrh** [comment]
Merged, thanks

**Pull request merged**
