### PR TITLE
Use the version of numpy compatible with a Python version

### PR DESCRIPTION
**Pull request by frenzymadness**
Fixes: https://github.com/sclorg/s2i-python-container/issues/341

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test-openshift]

**Comment by frenzymadness** [comment]
That's a strange error. @pkubatrh do you know where the problem may come from?

**Comment by pkubatrh** [comment]
We have been seeing some issues with rhel8 CI due to the way the scripts are called inside the VM and this seems similar enough (missing permissions due to umask?).

@kubco2 might be able to help here, but I would say that the issue is not related to this change and can be fixed separately.

**Comment by pkubatrh** [comment]
LGTM

I verified rhel8 manually outside of our CI and the tests passed. The rest of the tests are green in CI, so mergings. Thanks!

**Pull request merged**
