### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by torsava**

### CODE REVIEW

**Comment by torsava** [comment]
[test]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by torsava** [comment]
[test]

**Comment by torsava** [comment]
[test-openshift]

**Comment by torsava** [comment]
[test]

**Comment by torsava** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
I guess this can be closed now?

**Comment by phracek** [comment]
@torsava What is the status of this PR? Can be closed or merged? From my point of view it LGTM.

**Comment by torsava** [comment]
These changes were already done. I just forgot to close this PR.

**Pull request closed without merging**
