### PR TITLE
Update usage script

### PR DESCRIPTION
**Pull request by fila43**

### CODE REVIEW

**Comment by fila43** [comment]
[test]

**Review by frenzymadness — CHANGES_REQUESTED** [review]
I'd rather mention the documentation first and then the specific case for OpenShift users. Something like:
```
There are multiple ways how to use this image documented in …

To run this image in OpenShift, use the oc command:
…
```

Does it make sense? I think that not everybody knows `oc` command.

I'm gonna investigate the tests failures, it seems to be something with upstream wheels/pip.

**Comment by fila43** [comment]
> I'd rather mention the documentation first and then the specific case for OpenShift users. Something like:
> 
> ```
> There are multiple ways how to use this image documented in …
> 
> To run this image in OpenShift, use the oc command:
> …
> ```
> 
> Does it make sense? I think that not everybody knows `oc` command.
> 
> I'm gonna investigate the tests failures, it seems to be something with upstream wheels/pip.

Yea, good idea

**Comment by frenzymadness** [comment]
Tests are fixed in #417 , please rebase this PR along the way.

**Comment by fila43** [comment]
[test]

**Review by frenzymadness — APPROVED** [review]
Good job! Thank you!

**Pull request merged**
