### PR TITLE
build Fedora and CentOS Stream images also for arm64

### PR DESCRIPTION
**Pull request by zmiklank**
Depends on: https://github.com/sclorg/s2i-base-container/pull/292
Resolves: https://github.com/sclorg/s2i-python-container/issues/659

### CODE REVIEW

**Review by phracek — APPROVED** [review]
LGTM. But question. Why to not enable all archs like in postgresql-container
```
archs: amd64, s390x, ppc64le, arm64
```

I think the new request will come soon if we support part of architectures https://github.com/sclorg/postgresql-container/blob/master/.github/workflows/build-and-push.yml#L121

**Comment by zmiklank** [comment]
> LGTM. But question. Why to not enable all archs like in postgresql-container

Sure, we can do that. I was going with minimal option, but I am OK also with enabling all the arch. If not for python, then at least for s2i base and core. Should I update the PR accordingly?

**Comment by pkubatrh** [comment]
+1 to enabling all for s2i-core and s2i-base (since we already build all for postgresql anyway), I would keep only arm for python, as we didnt get any requests for other architectures yet.

**Comment by zmiklank** [comment]
Done for s2i-base and s2i-core:
https://github.com/sclorg/s2i-base-container/pull/292/

**Review by frenzymadness — APPROVED** [review]
I like it and I'm fine with minimum approach here and all architectures for base and core.

**Pull request merged**
