### PR TITLE
fail tests for specific app when prep. fails

### PR DESCRIPTION
**Pull request by zmiklank**
Fixes: https://github.com/sclorg/s2i-python-container/issues/593

Depends on: https://github.com/sclorg/container-common-scripts/pull/338

Also I have a question. Could it make sense to have the test/run files generated by distgen only as symlinks?

### CODE REVIEW

**Comment by frenzymadness** [comment]
> Also I have a question. Could it make sense to have the test/run files generated by distgen only as symlinks?

It's not possible right now because the files look different for full and minimal container images, and for Python 2 and 3+ images etc. (search for `{%` to see all templating done in the source file) but that might be something we can solve by some bash logic instead of the logic in the template we have there now. What would be the benefit of doing that?

**Comment by zmiklank** [comment]
> > Also I have a question. Could it make sense to have the test/run files generated by distgen only as symlinks?
> 
> It's not possible right now because the files look different for full and minimal container images, and for Python 2 and 3+ images etc. (search for `{%` to see all templating done in the source file) but that might be something we can solve by some bash logic instead of the logic in the template we have there now. What would be the benefit of doing that?

Right, if there is some reason behind it I am OK with that, thanks for explanation.

**Comment by zmiklank** [comment]
[test-all]

**Review by Lupphes — APPROVED** [review]
LGTM, tests passed

**Pull request merged**
