### PR TITLE
do not end line from readlink with NUL

### PR DESCRIPTION
**Pull request by zmiklank**
Source: https://github.com/sclorg/s2i-perl-container/pull/216

### CODE REVIEW

**Comment by phracek** [comment]
This affects only container tests.

[test]

**Comment by zmiklank** [comment]
Hmm, there is the "Couldn't resolve host name for https://mirrors.fedoraproject.org/" bug in the Fedora tests.

**Comment by frenzymadness** [comment]
Thanks for the PR. I've switched it to the draft because we use distgen in this repository so I can transfer the change to it.

**Comment by frenzymadness** [comment]
So, what I did here is that I split the one commit into two. The first one is the actual change to the source code and the second one contains changes propagated by distgen to the generated folders. This brings the change also to 3.10, omits unsupported version 3.3, and contains also manual change to 3.9-minimal which is not yet covered by distgen.

[test-all]

**Comment by frenzymadness** [comment]
There was no need to start OS tests and we know about the issue with Fedora Testing farm. It seems ready to be merged. Any last comments?

**Comment by zmiklank** [comment]
No, thanks for adjusting the PR.

**Comment by frenzymadness** [comment]
I thank you!

**Pull request merged**
